namespace Entitas.CodeGeneration {
    public class AddHeaderToFileProcessor : IPostProcessor {
        
        public const string AUTO_GENERATED_HEADER_FORMAT = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by {0}.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";
        
        public void Process(CodeGenFile[] codegenFiles) {
            foreach (var file in codegenFiles) {
                var header = string.Format(AUTO_GENERATED_HEADER_FORMAT, file.generatorName);
                file.fileContent = header + file.fileContent;
            }
        }
    }
}

