using NSpec;
using Entitas.CodeGeneration;

class describe_AddHeaderToFileProcessor : nspec {
    const string EXPECTED_HEADER = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by TestGeneratorName.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

    const string FILE_CONTENT = "this.is= new Filecontent()";

    const string GENERATOR_NAME = "TestGeneratorName";

    void process_files() {
        it["adds header to filecontent"] = () => {
            var processor = new AddHeaderToFileProcessor();

            var testFile = new CodeGenFile();
            testFile.fileContent = FILE_CONTENT;
            testFile.generatorName = GENERATOR_NAME;

            processor.Process(new []{ testFile });

            testFile.fileContent.should_be(EXPECTED_HEADER + FILE_CONTENT);
        };
    }
}


