namespace Entitas.Generators;

public static class Templates
{
    public static string GeneratedFileHeader(Type generatorType)
    {
        return $$"""
                //------------------------------------------------------------------------------
                // <auto-generated>
                //     This code was generated by
                //     {{generatorType}}
                //
                //     Changes to this file may cause incorrect behavior and will be lost if
                //     the code is regenerated.
                // </auto-generated>
                //------------------------------------------------------------------------------
                """;
    }

    public static string NamespaceDeclaration(string? @namespace)
    {
        return @namespace is not null
            ? $"namespace {@namespace};\n"
            : string.Empty;
    }
}
