//HintName: MyFeature.UniqueNamespacedComponent.MyApp.Main.ContextExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ContextExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using global::MyApp.Main;

namespace MyFeature
{
public static class MyAppMainUniqueNamespacedContextExtension
{
    public static Entity SetUniqueNamespaced(this MyApp.MainContext context)
    {
        return context.GetUniqueNamespacedEntity() ?? context.CreateEntity().SetUniqueNamespaced();
    }

    public static void UnsetUniqueNamespaced(this MyApp.MainContext context)
    {
        context.GetUniqueNamespacedEntity()?.Destroy();
    }

    public static Entity? GetUniqueNamespacedEntity(this MyApp.MainContext context)
    {
        return context.GetGroup(MyAppMainUniqueNamespacedMatcher.UniqueNamespaced).GetSingleEntity();
    }

    public static UniqueNamespacedComponent? GetUniqueNamespaced(this MyApp.MainContext context)
    {
        return context.GetUniqueNamespacedEntity()?.GetUniqueNamespaced();
    }
}
}
