//HintName: MyFeature.ReservedKeywordFieldsNamespacedComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainReservedKeywordFieldsNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainReservedKeywordFieldsNamespacedEntityExtension
{
    public static bool HasReservedKeywordFieldsNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddReservedKeywordFieldsNamespaced(this Entity entity, string @namespace, string @class, string @public)
    {
        var index = Index.Value;
        var component = (ReservedKeywordFieldsNamespacedComponent)entity.CreateComponent(index, typeof(ReservedKeywordFieldsNamespacedComponent));
        component.Namespace = @namespace;
        component.Class = @class;
        component.Public = @public;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceReservedKeywordFieldsNamespaced(this Entity entity, string @namespace, string @class, string @public)
    {
        var index = Index.Value;
        var component = (ReservedKeywordFieldsNamespacedComponent)entity.CreateComponent(index, typeof(ReservedKeywordFieldsNamespacedComponent));
        component.Namespace = @namespace;
        component.Class = @class;
        component.Public = @public;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveReservedKeywordFieldsNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static ReservedKeywordFieldsNamespacedComponent GetReservedKeywordFieldsNamespaced(this Entity entity)
    {
        return (ReservedKeywordFieldsNamespacedComponent)entity.GetComponent(Index.Value);
    }
}
}
