//HintName: FakeGenerated.EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedEntityExtensions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtensions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace FakeGenerated
{
public static class EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedEntityExtensions
{
    static readonly Entitas.Generators.Tests.Fixtures.Components.OneContextNamespacedComponent SingleOneContextNamespacedComponent = new Entitas.Generators.Tests.Fixtures.Components.OneContextNamespacedComponent();

    public static bool HasOneContextNamespaced(this FakeGenerated.Entity entity)
    {
        return entity.HasComponent(EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedComponentIndex.Value);
    }

    public static FakeGenerated.Entity AddOneContextNamespaced(this FakeGenerated.Entity entity)
    {
        entity.AddComponent(EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedComponentIndex.Value, SingleOneContextNamespacedComponent);
        return entity;
    }

    public static FakeGenerated.Entity ReplaceOneContextNamespaced(this FakeGenerated.Entity entity)
    {
        entity.ReplaceComponent(EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedComponentIndex.Value, SingleOneContextNamespacedComponent);
        return entity;
    }

    public static FakeGenerated.Entity RemoveOneContextNamespaced(this FakeGenerated.Entity entity)
    {
        entity.RemoveComponent(EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedComponentIndex.Value);
        return entity;
    }
}
}
