//HintName: MyAppMainSomeMatcher.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Matcher
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed class MyAppMainSomeMatcher
{
    static global::Entitas.IMatcher<global::MyApp.Main.Entity> _matcher;

    public static global::Entitas.IMatcher<global::MyApp.Main.Entity> Some
    {
        get
        {
            if (_matcher == null)
            {
                var matcher = (global::Entitas.Matcher<global::MyApp.Main.Entity>)global::Entitas.Matcher<global::MyApp.Main.Entity>.AllOf(MyAppMainSomeComponentIndex.Index.Value);
                matcher.componentNames = MyApp.MainContext.ComponentNames;
                _matcher = matcher;
            }

            return _matcher;
        }
    }
}
