//HintName: MyFeature.MyAppMainSelfEventNamespacedRemovedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

namespace MyFeature
{
public interface IMyAppMainSelfEventNamespacedRemovedListener
{
    void OnSelfEventNamespacedRemoved(Entity entity, string value);
}

public sealed class MyAppMainSelfEventNamespacedRemovedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainSelfEventNamespacedRemovedListener> Value;
}

public static class MyAppMainSelfEventNamespacedRemovedListenerEventEntityExtension
{
    public static void AddSelfEventNamespacedRemovedListener(this Entity entity, IMyAppMainSelfEventNamespacedRemovedListener value)
    {
        var listeners = entity.HasSelfEventNamespacedRemovedListener()
            ? entity.GetSelfEventNamespacedRemovedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainSelfEventNamespacedRemovedListener>();
        listeners.Add(value);
        entity.ReplaceSelfEventNamespacedRemovedListener(listeners);
    }

    public static void RemoveSelfEventNamespacedRemovedListener(this Entity entity, IMyAppMainSelfEventNamespacedRemovedListener value, bool removeComponentWhenEmpty = true)
    {
        var listeners = entity.GetSelfEventNamespacedRemovedListener().Value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveSelfEventNamespacedRemovedListener();
        }
        else
        {
            entity.ReplaceSelfEventNamespacedRemovedListener(listeners);
        }
    }
}}
