//HintName: MyAppMainAnyFlagEventRemovedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

public interface IMyAppMainAnyFlagEventRemovedListener
{
    void OnAnyFlagEventRemoved(Entity entity);
}

public sealed class MyAppMainAnyFlagEventRemovedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainAnyFlagEventRemovedListener> Value;
}

public static class MyAppMainAnyFlagEventRemovedListenerEventEntityExtension
{
    public static Entity AddAnyFlagEventRemovedListener(this Entity entity, IMyAppMainAnyFlagEventRemovedListener value)
    {
        var listeners = entity.HasAnyFlagEventRemovedListener()
            ? entity.GetAnyFlagEventRemovedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainAnyFlagEventRemovedListener>();
        listeners.Add(value);
        return entity.ReplaceAnyFlagEventRemovedListener(listeners);
    }

    public static void RemoveAnyFlagEventRemovedListener(this Entity entity, IMyAppMainAnyFlagEventRemovedListener value, bool removeListenerWhenEmpty = true)
    {
        var listeners = entity.GetAnyFlagEventRemovedListener().Value;
        listeners.Remove(value);
        if (removeListenerWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveAnyFlagEventRemovedListener();
            if (entity.IsEmpty())
                entity.Destroy();
        }
        else
        {
            entity.ReplaceAnyFlagEventRemovedListener(listeners);
        }
    }
}

public sealed class MyAppMainAnyFlagEventRemovedEventSystem : global::Entitas.ReactiveSystem<Entity>
{
    readonly global::Entitas.IGroup<Entity> _listeners;
    readonly global::System.Collections.Generic.List<Entity> _entityBuffer;
    readonly global::System.Collections.Generic.List<IMyAppMainAnyFlagEventRemovedListener> _listenerBuffer;

    public MyAppMainAnyFlagEventRemovedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listeners = context.GetGroup(MyAppMainAnyFlagEventRemovedListenerMatcher.AnyFlagEventRemovedListener);
        _entityBuffer = new global::System.Collections.Generic.List<Entity>();
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainAnyFlagEventRemovedListener>();
    }

    protected override global::Entitas.ICollector<Entity> GetTrigger(global::Entitas.IContext<Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Added(MyAppMainFlagEventMatcher.FlagEvent)
        );
    }

    protected override bool Filter(Entity entity)
    {
        return !entity.HasFlagEvent();
    }

    protected override void Execute(global::System.Collections.Generic.List<Entity> entities)
    {
        foreach (var entity in entities)
        {
            foreach (var listenerEntity in _listeners.GetEntities(_entityBuffer))
            {
                _listenerBuffer.Clear();
                _listenerBuffer.AddRange(listenerEntity.GetAnyFlagEventRemovedListener().Value);
                foreach (var listener in _listenerBuffer)
                {
                    listener.OnAnyFlagEventRemoved(entity);
                }
            }
        }
    }
}
