//HintName: MyFeature.MyAppMainNoValidFieldsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainNoValidFieldsNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainNoValidFieldsNamespacedEntityExtension
{
    static readonly NoValidFieldsNamespacedComponent SingleNoValidFieldsNamespacedComponent = new NoValidFieldsNamespacedComponent();

    public static bool HasNoValidFieldsNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddNoValidFieldsNamespaced(this Entity entity)
    {
        entity.AddComponent(Index.Value, SingleNoValidFieldsNamespacedComponent);
        return entity;
    }

    public static Entity ReplaceNoValidFieldsNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleNoValidFieldsNamespacedComponent);
        return entity;
    }

    public static Entity RemoveNoValidFieldsNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static NoValidFieldsNamespacedComponent GetNoValidFieldsNamespaced(this Entity entity)
    {
        return (NoValidFieldsNamespacedComponent)entity.GetComponent(Index.Value);
    }
}
}
