//HintName: MyFeature.DuplicatedContextsNamespacedComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using global::MyApp.Main;
using static global::MyFeature.MyAppMainDuplicatedContextsNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainDuplicatedContextsNamespacedEntityExtension
{
    static readonly DuplicatedContextsNamespacedComponent SingleDuplicatedContextsNamespacedComponent = new DuplicatedContextsNamespacedComponent();

    public static Entity SetDuplicatedContextsNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleDuplicatedContextsNamespacedComponent);
        return entity;
    }

    public static Entity UnsetDuplicatedContextsNamespaced(this Entity entity)
    {
        if (entity.HasComponent(Index.Value))
            entity.RemoveComponent(Index.Value);

        return entity;
    }

    public static DuplicatedContextsNamespacedComponent? GetDuplicatedContextsNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value)
            ? (DuplicatedContextsNamespacedComponent)entity.GetComponent(Index.Value)
            : null;
    }
}
}
