//HintName: Other.MyAppMultipleFieldsNamespacedComponentIndex.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ComponentIndex
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Other
{
public static class MyAppMultipleFieldsNamespacedComponentIndex
{
    public static ComponentIndex Value;
}
}
