//HintName: MyApp.LibraryContext.EventSystemsExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EventSystemsContextExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Library;

namespace MyApp
{
public static class LibraryContextEventSystemsExtension
{
    public static global::Entitas.Systems CreateEventSystems(this LibraryContext context)
    {
        var systems = new global::Entitas.Systems();
        systems.Add(new MyOtherFeature.MyAppLibraryCollisionAddedEventSystem(context)); // order: 1
        return systems;
    }
}
}
