//HintName: EmptyContextCleanupSystemsExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.CleanupSystems
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class EmptyContextCleanupSystemsExtension
{
    public static global::Entitas.Systems CreateCleanupSystems(this EmptyContext context)
    {
        return null;
    }
}
