//HintName: MyFeature.MyAppMainAnyFlagEventNamespacedRemovedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

namespace MyFeature
{
public interface IMyAppMainAnyFlagEventNamespacedRemovedListener
{
    void OnAnyFlagEventNamespacedRemoved(Entity entity);
}

public sealed class MyAppMainAnyFlagEventNamespacedRemovedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainAnyFlagEventNamespacedRemovedListener> Value;
}

public static class MyAppMainAnyFlagEventNamespacedRemovedListenerEventEntityExtension
{
    public static Entity AddAnyFlagEventNamespacedRemovedListener(this Entity entity, IMyAppMainAnyFlagEventNamespacedRemovedListener value)
    {
        var listeners = entity.HasAnyFlagEventNamespacedRemovedListener()
            ? entity.GetAnyFlagEventNamespacedRemovedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainAnyFlagEventNamespacedRemovedListener>();
        listeners.Add(value);
        return entity.ReplaceAnyFlagEventNamespacedRemovedListener(listeners);
    }

    public static void RemoveAnyFlagEventNamespacedRemovedListener(this Entity entity, IMyAppMainAnyFlagEventNamespacedRemovedListener value, bool destroyListenerWhenEmpty = true)
    {
        var listeners = entity.GetAnyFlagEventNamespacedRemovedListener().Value;
        listeners.Remove(value);
        if (destroyListenerWhenEmpty && listeners.Count == 0)
            entity.Destroy();
        else
            entity.ReplaceAnyFlagEventNamespacedRemovedListener(listeners);
    }
}

public sealed class MyAppMainAnyFlagEventNamespacedRemovedEventSystem : global::Entitas.ReactiveSystem<Entity>
{
    readonly global::Entitas.IGroup<Entity> _listeners;
    readonly global::System.Collections.Generic.List<Entity> _entityBuffer;
    readonly global::System.Collections.Generic.List<IMyAppMainAnyFlagEventNamespacedRemovedListener> _listenerBuffer;

    public MyAppMainAnyFlagEventNamespacedRemovedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listeners = context.GetGroup(MyAppMainAnyFlagEventNamespacedRemovedListenerMatcher.AnyFlagEventNamespacedRemovedListener);
        _entityBuffer = new global::System.Collections.Generic.List<Entity>();
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainAnyFlagEventNamespacedRemovedListener>();
    }

    protected override global::Entitas.ICollector<Entity> GetTrigger(global::Entitas.IContext<Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Added(MyAppMainFlagEventNamespacedMatcher.FlagEventNamespaced)
        );
    }

    protected override bool Filter(Entity entity)
    {
        return !entity.HasFlagEventNamespaced();
    }

    protected override void Execute(global::System.Collections.Generic.List<Entity> entities)
    {
        foreach (var entity in entities)
        {
            foreach (var listenerEntity in _listeners.GetEntities(_entityBuffer))
            {
                _listenerBuffer.Clear();
                _listenerBuffer.AddRange(listenerEntity.GetAnyFlagEventNamespacedRemovedListener().Value);
                foreach (var listener in _listenerBuffer)
                {
                    listener.OnAnyFlagEventNamespacedRemoved(entity);
                }
            }
        }
    }
}
}
