//HintName: MyFeature.NoValidFieldsNamespacedComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using global::MyApp.Main;
using static global::MyFeature.MyAppMainNoValidFieldsNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainNoValidFieldsNamespacedEntityExtension
{
    static readonly NoValidFieldsNamespacedComponent SingleNoValidFieldsNamespacedComponent = new NoValidFieldsNamespacedComponent();

    public static Entity SetNoValidFieldsNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleNoValidFieldsNamespacedComponent);
        return entity;
    }

    public static Entity UnsetNoValidFieldsNamespaced(this Entity entity)
    {
        if (entity.HasComponent(Index.Value))
            entity.RemoveComponent(Index.Value);

        return entity;
    }

    public static NoValidFieldsNamespacedComponent? GetNoValidFieldsNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value)
            ? (NoValidFieldsNamespacedComponent)entity.GetComponent(Index.Value)
            : null;
    }
}
}
