//HintName: MyApp.MainContextEventSystemsExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EventSystemsContextExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp
{
public static class MainContextEventSystemsExtension
{
    public static global::Entitas.Systems CreateEventSystems(this MainContext context)
    {
        var systems = new global::Entitas.Systems();
        systems.Add(new global::MyAppMainAnyEventAddedEventSystem(context)); // Order: 1
        systems.Add(new global::MyAppMainAnyFlagEventAddedEventSystem(context)); // Order: 1
        systems.Add(new global::MyFeature.MyAppMainAnyEventNamespacedAddedEventSystem(context)); // Order: 1
        systems.Add(new global::MyFeature.MyAppMainAnyFlagEventNamespacedAddedEventSystem(context)); // Order: 1
        systems.Add(new global::MyAppMainAnyEventRemovedEventSystem(context)); // Order: 2
        systems.Add(new global::MyAppMainAnyFlagEventRemovedEventSystem(context)); // Order: 2
        systems.Add(new global::MyFeature.MyAppMainAnyEventNamespacedRemovedEventSystem(context)); // Order: 2
        systems.Add(new global::MyFeature.MyAppMainAnyFlagEventNamespacedRemovedEventSystem(context)); // Order: 2
        systems.Add(new global::MyAppMainEventAddedEventSystem(context)); // Order: 3
        systems.Add(new global::MyAppMainFlagEventAddedEventSystem(context)); // Order: 3
        systems.Add(new global::MyFeature.MyAppMainEventNamespacedAddedEventSystem(context)); // Order: 3
        systems.Add(new global::MyFeature.MyAppMainFlagEventNamespacedAddedEventSystem(context)); // Order: 3
        systems.Add(new global::MyAppMainEventRemovedEventSystem(context)); // Order: 4
        systems.Add(new global::MyAppMainFlagEventRemovedEventSystem(context)); // Order: 4
        systems.Add(new global::MyFeature.MyAppMainEventNamespacedRemovedEventSystem(context)); // Order: 4
        systems.Add(new global::MyFeature.MyAppMainFlagEventNamespacedRemovedEventSystem(context)); // Order: 4
        return systems;
    }
}
}
