//HintName: MyFeature.MyAppMainUniqueNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyFeature
{
public static class MyAppMainUniqueNamespacedEntityExtension
{
    static readonly UniqueNamespacedComponent SingleUniqueNamespacedComponent = new UniqueNamespacedComponent();

    public static bool HasUniqueNamespaced(this global::MyApp.Main.Entity entity)
    {
        return entity.HasComponent(MyAppMainUniqueNamespacedComponentIndex.Index.Value);
    }

    public static global::MyApp.Main.Entity AddUniqueNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.AddComponent(MyAppMainUniqueNamespacedComponentIndex.Index.Value, SingleUniqueNamespacedComponent);
        return entity;
    }

    public static global::MyApp.Main.Entity ReplaceUniqueNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.ReplaceComponent(MyAppMainUniqueNamespacedComponentIndex.Index.Value, SingleUniqueNamespacedComponent);
        return entity;
    }

    public static global::MyApp.Main.Entity RemoveUniqueNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(MyAppMainUniqueNamespacedComponentIndex.Index.Value);
        return entity;
    }

    public static UniqueNamespacedComponent GetUniqueNamespaced(this global::MyApp.Main.Entity entity)
    {
        return (UniqueNamespacedComponent)entity.GetComponent(MyAppMainUniqueNamespacedComponentIndex.Index.Value);
    }
}
}
