//HintName: Entitas.Generators.Tests.Fixtures.NamespacedComponentWithOneField.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas.Generators.Tests.Fixtures;

public static class NamespacedComponentWithOneFieldExtensions
{
    public static string GetValue(this object entity)
    {
        return default;
    }
}
