//HintName: MyFeature.MyAppMainSelfEventNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainSelfEventNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainSelfEventNamespacedEntityExtension
{
    public static bool HasSelfEventNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddSelfEventNamespaced(this Entity entity, string value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (SelfEventNamespacedComponent)componentPool.Pop()
            : new SelfEventNamespacedComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceSelfEventNamespaced(this Entity entity, string value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (SelfEventNamespacedComponent)componentPool.Pop()
            : new SelfEventNamespacedComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveSelfEventNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static SelfEventNamespacedComponent GetSelfEventNamespaced(this Entity entity)
    {
        return (SelfEventNamespacedComponent)entity.GetComponent(Index.Value);
    }
}
}
