//HintName: Other.SomeEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Other
{
public static class SomeEntityExtension
{
    static readonly SomeComponent SingleSomeComponent = new SomeComponent();

    public static bool HasSome(this Entity entity)
    {
        return entity.HasComponent(SomeComponentIndex.Value);
    }

    public static Entity AddSome(this Entity entity)
    {
        entity.AddComponent(SomeComponentIndex.Value, SingleSomeComponent);
        return entity;
    }

    public static Entity ReplaceSome(this Entity entity)
    {
        entity.ReplaceComponent(SomeComponentIndex.Value, SingleSomeComponent);
        return entity;
    }

    public static Entity RemoveSome(this Entity entity)
    {
        entity.RemoveComponent(SomeComponentIndex.Value);
        return entity;
    }
}
}
