//HintName: SomeComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using global::MyApp.Main;
using static global::MyAppMainSomeComponentIndex;

public static class MyAppMainSomeEntityExtension
{
    static readonly SomeComponent SingleSomeComponent = new SomeComponent();

    public static Entity SetSome(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleSomeComponent);
        return entity;
    }

    public static Entity UnsetSome(this Entity entity)
    {
        if (entity.HasComponent(Index.Value))
            entity.RemoveComponent(Index.Value);

        return entity;
    }

    public static SomeComponent? GetSome(this Entity entity)
    {
        return entity.HasComponent(Index.Value)
            ? (SomeComponent)entity.GetComponent(Index.Value)
            : null;
    }
}
