//HintName: EmptyContextEntityIndexExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityIndexExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class EmptyContextEntityIndexExtension
{
    public static EmptyContext AddAllEntityIndexes(this EmptyContext context)
    {
        return context;
    }
}
