//HintName: MyAppMainAnyFlagEventAddedListenerEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyAppMainAnyFlagEventAddedListenerComponentIndex;

public static class MyAppMainAnyFlagEventAddedListenerEntityExtension
{
    public static bool HasAnyFlagEventAddedListener(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddAnyFlagEventAddedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainAnyFlagEventAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainAnyFlagEventAddedListenerComponent)componentPool.Pop()
            : new MyAppMainAnyFlagEventAddedListenerComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceAnyFlagEventAddedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainAnyFlagEventAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainAnyFlagEventAddedListenerComponent)componentPool.Pop()
            : new MyAppMainAnyFlagEventAddedListenerComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveAnyFlagEventAddedListener(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MyAppMainAnyFlagEventAddedListenerComponent GetAnyFlagEventAddedListener(this Entity entity)
    {
        return (MyAppMainAnyFlagEventAddedListenerComponent)entity.GetComponent(Index.Value);
    }
}
