//HintName: MyApp.MainContext.ContextInitializationMethod.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ContextInitializationMethod
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using MyApp.Main;

namespace MyApp
{
public static partial class ContextInitialization
{
    public static partial void Initialize()
    {
        MyFeatureAnotherNamespacedComponentIndex.Index = new ComponentIndex(0);
        MyFeatureSomeNamespacedComponentIndex.Index = new ComponentIndex(1);

        MyApp.MainContext.ComponentNames = new string[]
        {
            "MyFeature.AnotherNamespaced",
            "MyFeature.SomeNamespaced"
        };

        MyApp.MainContext.ComponentTypes = new System.Type[]
        {
            typeof(MyFeature.AnotherNamespacedComponent),
            typeof(MyFeature.SomeNamespacedComponent)
        };
    }
}
}
