//HintName: MyFeature.MyAppMainEventNamespacedAddedListenerEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainEventNamespacedAddedListenerComponentIndex;

namespace MyFeature
{
public static class MyAppMainEventNamespacedAddedListenerEntityExtension
{
    public static bool HasEventNamespacedAddedListener(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddEventNamespacedAddedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainEventNamespacedAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainEventNamespacedAddedListenerComponent)componentPool.Pop()
            : new MyAppMainEventNamespacedAddedListenerComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceEventNamespacedAddedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainEventNamespacedAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainEventNamespacedAddedListenerComponent)componentPool.Pop()
            : new MyAppMainEventNamespacedAddedListenerComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveEventNamespacedAddedListener(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MyAppMainEventNamespacedAddedListenerComponent GetEventNamespacedAddedListener(this Entity entity)
    {
        return (MyAppMainEventNamespacedAddedListenerComponent)entity.GetComponent(Index.Value);
    }
}
}
