//HintName: MyFeature.ReservedKeywordFieldsNamespacedComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using global::MyApp.Main;
using static global::MyFeature.MyAppMainReservedKeywordFieldsNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainReservedKeywordFieldsNamespacedEntityExtension
{
    public static Entity SetReservedKeywordFieldsNamespaced(this Entity entity, string @namespace, string @class, string @public)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ReservedKeywordFieldsNamespacedComponent)componentPool.Pop()
            : new ReservedKeywordFieldsNamespacedComponent();
        component.Namespace = @namespace;
        component.Class = @class;
        component.Public = @public;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity UnsetReservedKeywordFieldsNamespaced(this Entity entity)
    {
        if (entity.HasComponent(Index.Value))
            entity.RemoveComponent(Index.Value);

        return entity;
    }

    public static ReservedKeywordFieldsNamespacedComponent? GetReservedKeywordFieldsNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value)
            ? (ReservedKeywordFieldsNamespacedComponent)entity.GetComponent(Index.Value)
            : null;
    }
}
}
