//HintName: MyFeature.UniqueNamespacedComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainUniqueNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainUniqueNamespacedEntityExtension
{
    static readonly UniqueNamespacedComponent SingleUniqueNamespacedComponent = new UniqueNamespacedComponent();

    public static bool HasUniqueNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddUniqueNamespaced(this Entity entity)
    {
        entity.AddComponent(Index.Value, SingleUniqueNamespacedComponent);
        return entity;
    }

    public static Entity ReplaceUniqueNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleUniqueNamespacedComponent);
        return entity;
    }

    public static Entity RemoveUniqueNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static UniqueNamespacedComponent GetUniqueNamespaced(this Entity entity)
    {
        return (UniqueNamespacedComponent)entity.GetComponent(Index.Value);
    }
}
}
