//HintName: MyAppMainFlagEventAddedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

public interface IMyAppMainFlagEventAddedListener
{
    void OnFlagEventAdded(Entity entity);
}

public sealed class MyAppMainFlagEventAddedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainFlagEventAddedListener> Value;
}

public static class MyAppMainFlagEventAddedListenerEventEntityExtension
{
    public static Entity AddFlagEventAddedListener(this Entity entity, IMyAppMainFlagEventAddedListener value)
    {
        var listeners = entity.HasFlagEventAddedListener()
            ? entity.GetFlagEventAddedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainFlagEventAddedListener>();
        listeners.Add(value);
        return entity.ReplaceFlagEventAddedListener(listeners);
    }

    public static void RemoveFlagEventAddedListener(this Entity entity, IMyAppMainFlagEventAddedListener value, bool removeListenerWhenEmpty = true)
    {
        var listeners = entity.GetFlagEventAddedListener().Value;
        listeners.Remove(value);
        if (removeListenerWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveFlagEventAddedListener();
            if (entity.IsEmpty())
                entity.Destroy();
        }
        else
        {
            entity.ReplaceFlagEventAddedListener(listeners);
        }
    }
}

public sealed class MyAppMainFlagEventAddedEventSystem : global::Entitas.ReactiveSystem<Entity>
{
    readonly global::System.Collections.Generic.List<IMyAppMainFlagEventAddedListener> _listenerBuffer;

    public MyAppMainFlagEventAddedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainFlagEventAddedListener>();
    }

    protected override global::Entitas.ICollector<Entity> GetTrigger(global::Entitas.IContext<Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Added(MyAppMainFlagEventMatcher.FlagEvent)
        );
    }

    protected override bool Filter(Entity entity)
    {
        return entity.HasFlagEvent() && entity.HasFlagEventAddedListener();
    }

    protected override void Execute(global::System.Collections.Generic.List<Entity> entities)
    {
        foreach (var entity in entities)
        {
            _listenerBuffer.Clear();
            _listenerBuffer.AddRange(entity.GetFlagEventAddedListener().Value);
            foreach (var listener in _listenerBuffer)
            {
                listener.OnFlagEventAdded(entity);
            }
        }
    }
}
