//HintName: MyFeature.MyAppMainDuplicatedContextsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainDuplicatedContextsNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainDuplicatedContextsNamespacedEntityExtension
{
    static readonly DuplicatedContextsNamespacedComponent SingleDuplicatedContextsNamespacedComponent = new DuplicatedContextsNamespacedComponent();

    public static bool HasDuplicatedContextsNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddDuplicatedContextsNamespaced(this Entity entity)
    {
        entity.AddComponent(Index.Value, SingleDuplicatedContextsNamespacedComponent);
        return entity;
    }

    public static Entity ReplaceDuplicatedContextsNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleDuplicatedContextsNamespacedComponent);
        return entity;
    }

    public static Entity RemoveDuplicatedContextsNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static DuplicatedContextsNamespacedComponent GetDuplicatedContextsNamespaced(this Entity entity)
    {
        return (DuplicatedContextsNamespacedComponent)entity.GetComponent(Index.Value);
    }
}
}
