//HintName: MyApp.Main.MyFeatureNoValidFieldsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp.Main
{
public static class MyFeatureNoValidFieldsNamespacedEntityExtension
{
    static readonly MyFeature.NoValidFieldsNamespacedComponent SingleNoValidFieldsNamespacedComponent = new MyFeature.NoValidFieldsNamespacedComponent();

    public static MyFeature.NoValidFieldsNamespacedComponent GetNoValidFieldsNamespaced(this Entity entity)
    {
        return (MyFeature.NoValidFieldsNamespacedComponent)entity.GetComponent(MyFeatureNoValidFieldsNamespacedComponentIndex.Value);
    }

    public static bool HasNoValidFieldsNamespaced(this Entity entity)
    {
        return entity.HasComponent(MyFeatureNoValidFieldsNamespacedComponentIndex.Value);
    }

    public static Entity AddNoValidFieldsNamespaced(this Entity entity)
    {
        entity.AddComponent(MyFeatureNoValidFieldsNamespacedComponentIndex.Value, SingleNoValidFieldsNamespacedComponent);
        return entity;
    }

    public static Entity ReplaceNoValidFieldsNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(MyFeatureNoValidFieldsNamespacedComponentIndex.Value, SingleNoValidFieldsNamespacedComponent);
        return entity;
    }

    public static Entity RemoveNoValidFieldsNamespaced(this Entity entity)
    {
        entity.RemoveComponent(MyFeatureNoValidFieldsNamespacedComponentIndex.Value);
        return entity;
    }
}
}
