//HintName: MyFeature.UniqueOneFieldNamespacedComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using global::MyApp.Main;
using static global::MyFeature.MyAppMainUniqueOneFieldNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainUniqueOneFieldNamespacedEntityExtension
{
    public static Entity SetUniqueOneFieldNamespaced(this Entity entity, string value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (UniqueOneFieldNamespacedComponent)componentPool.Pop()
            : new UniqueOneFieldNamespacedComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity UnsetUniqueOneFieldNamespaced(this Entity entity)
    {
        if (entity.HasComponent(Index.Value))
            entity.RemoveComponent(Index.Value);

        return entity;
    }

    public static UniqueOneFieldNamespacedComponent? GetUniqueOneFieldNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value)
            ? (UniqueOneFieldNamespacedComponent)entity.GetComponent(Index.Value)
            : null;
    }
}
}
