//HintName: MyAppMainFlagEventAddedListenerEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyAppMainFlagEventAddedListenerComponentIndex;

public static class MyAppMainFlagEventAddedListenerEntityExtension
{
    public static bool HasFlagEventAddedListener(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddFlagEventAddedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainFlagEventAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainFlagEventAddedListenerComponent)componentPool.Pop()
            : new MyAppMainFlagEventAddedListenerComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceFlagEventAddedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainFlagEventAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainFlagEventAddedListenerComponent)componentPool.Pop()
            : new MyAppMainFlagEventAddedListenerComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveFlagEventAddedListener(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MyAppMainFlagEventAddedListenerComponent GetFlagEventAddedListener(this Entity entity)
    {
        return (MyAppMainFlagEventAddedListenerComponent)entity.GetComponent(Index.Value);
    }
}
