//HintName: MyFeature.EventNamespacedComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainEventNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainEventNamespacedEntityExtension
{
    public static bool HasEventNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddEventNamespaced(this Entity entity, string value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (EventNamespacedComponent)componentPool.Pop()
            : new EventNamespacedComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceEventNamespaced(this Entity entity, string value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (EventNamespacedComponent)componentPool.Pop()
            : new EventNamespacedComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveEventNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static EventNamespacedComponent GetEventNamespaced(this Entity entity)
    {
        return (EventNamespacedComponent)entity.GetComponent(Index.Value);
    }
}
}
