//HintName: MyApp.Main.MultipleFieldsEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp.Main
{
public static class MultipleFieldsEntityExtension
{
    public static bool HasMultipleFields(this MyApp.Main.Entity entity)
    {
        return entity.HasComponent(MultipleFieldsComponentIndex.Value);
    }

    public static MyApp.Main.Entity AddMultipleFields(this MyApp.Main.Entity entity, string value1, string value2, string value3)
    {
        var index = MultipleFieldsComponentIndex.Value;
        var component = (MultipleFieldsComponent)entity.CreateComponent(index, typeof(MultipleFieldsComponent));
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.AddComponent(index, component);
        return entity;
    }

    public static MyApp.Main.Entity ReplaceMultipleFields(this MyApp.Main.Entity entity, string value1, string value2, string value3)
    {
        var index = MultipleFieldsComponentIndex.Value;
        var component = (MultipleFieldsComponent)entity.CreateComponent(index, typeof(MultipleFieldsComponent));
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static MyApp.Main.Entity RemoveMultipleFields(this MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(MultipleFieldsComponentIndex.Value);
        return entity;
    }
}
}
