//HintName: MyFeature.MyAppMainSomeNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyFeature
{
public static class MyAppMainSomeNamespacedEntityExtension
{
    static readonly SomeNamespacedComponent SingleSomeNamespacedComponent = new SomeNamespacedComponent();

    public static bool HasSomeNamespaced(this global::MyApp.Main.Entity entity)
    {
        return entity.HasComponent(MyAppMainSomeNamespacedComponentIndex.Index.Value);
    }

    public static global::MyApp.Main.Entity AddSomeNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.AddComponent(MyAppMainSomeNamespacedComponentIndex.Index.Value, SingleSomeNamespacedComponent);
        return entity;
    }

    public static global::MyApp.Main.Entity ReplaceSomeNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.ReplaceComponent(MyAppMainSomeNamespacedComponentIndex.Index.Value, SingleSomeNamespacedComponent);
        return entity;
    }

    public static global::MyApp.Main.Entity RemoveSomeNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(MyAppMainSomeNamespacedComponentIndex.Index.Value);
        return entity;
    }

    public static SomeNamespacedComponent GetSomeNamespaced(this global::MyApp.Main.Entity entity)
    {
        return (SomeNamespacedComponent)entity.GetComponent(MyAppMainSomeNamespacedComponentIndex.Index.Value);
    }
}
}
