//HintName: MyFeature.AnyMyAppMainAnyEventNamespacedAddedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

namespace MyFeature
{
public interface IAnyMyAppMainAnyEventNamespacedAddedListener
{
    void OnAnyAnyEventNamespacedAdded(Entity entity, string value);
}

public sealed class AnyMyAppMainAnyEventNamespacedAddedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IAnyMyAppMainAnyEventNamespacedAddedListener> Value;
}

public static class AnyMyAppMainAnyEventNamespacedAddedListenerEventEntityExtension
{
    public static void AddAnyAnyEventNamespacedAddedListener(this Entity entity, IAnyMyAppMainAnyEventNamespacedAddedListener value)
    {
        var listeners = entity.HasAnyAnyEventNamespacedAddedListener()
            ? entity.GetAnyAnyEventNamespacedAddedListener().Value
            : new global::System.Collections.Generic.List<IAnyMyAppMainAnyEventNamespacedAddedListener>();
        listeners.Add(value);
        entity.ReplaceAnyAnyEventNamespacedAddedListener(listeners);
    }

    public static void RemoveAnyAnyEventNamespacedAddedListener(this Entity entity, IAnyMyAppMainAnyEventNamespacedAddedListener value, bool removeComponentWhenEmpty = true)
    {
        var listeners = entity.GetAnyAnyEventNamespacedAddedListener().Value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveAnyAnyEventNamespacedAddedListener();
        }
        else
        {
            entity.ReplaceAnyAnyEventNamespacedAddedListener(listeners);
        }
    }
}}
