//HintName: MyFeature.MyAppMainAnyEventNamespacedAddedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyFeature
{
public interface IMyAppMainAnyEventNamespacedAddedListener
{
    void OnAnyEventNamespacedAdded(global::MyApp.Main.Entity entity, string value);
}

public sealed class MyAppMainAnyEventNamespacedAddedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedAddedListener> Value;
}

public static class MyAppMainAnyEventNamespacedAddedListenerEventEntityExtension
{
    public static global::MyApp.Main.Entity AddAnyEventNamespacedAddedListener(this global::MyApp.Main.Entity entity, IMyAppMainAnyEventNamespacedAddedListener value)
    {
        var listeners = entity.HasAnyEventNamespacedAddedListener()
            ? entity.GetAnyEventNamespacedAddedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedAddedListener>();
        listeners.Add(value);
        return entity.ReplaceAnyEventNamespacedAddedListener(listeners);
    }

    public static void RemoveAnyEventNamespacedAddedListener(this global::MyApp.Main.Entity entity, IMyAppMainAnyEventNamespacedAddedListener value, bool removeListenerWhenEmpty = true)
    {
        var listeners = entity.GetAnyEventNamespacedAddedListener().Value;
        listeners.Remove(value);
        if (removeListenerWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveAnyEventNamespacedAddedListener();
            if (entity.IsEmpty())
                entity.Destroy();
        }
        else
        {
            entity.ReplaceAnyEventNamespacedAddedListener(listeners);
        }
    }
}

public sealed class MyAppMainAnyEventNamespacedAddedEventSystem : global::Entitas.ReactiveSystem<global::MyApp.Main.Entity>
{
    readonly global::Entitas.IGroup<global::MyApp.Main.Entity> _listeners;
    readonly global::System.Collections.Generic.List<global::MyApp.Main.Entity> _entityBuffer;
    readonly global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedAddedListener> _listenerBuffer;

    public MyAppMainAnyEventNamespacedAddedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listeners = context.GetGroup(MyAppMainAnyEventNamespacedAddedListenerMatcher.AnyEventNamespacedAddedListener);
        _entityBuffer = new global::System.Collections.Generic.List<global::MyApp.Main.Entity>();
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedAddedListener>();
    }

    protected override global::Entitas.ICollector<global::MyApp.Main.Entity> GetTrigger(global::Entitas.IContext<global::MyApp.Main.Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Added(MyAppMainEventNamespacedMatcher.EventNamespaced)
        );
    }

    protected override bool Filter(global::MyApp.Main.Entity entity)
    {
        return entity.HasEventNamespaced();
    }

    protected override void Execute(global::System.Collections.Generic.List<global::MyApp.Main.Entity> entities)
    {
        foreach (var entity in entities)
        {
            var component = entity.GetEventNamespaced();
            foreach (var listenerEntity in _listeners.GetEntities(_entityBuffer))
            {
                _listenerBuffer.Clear();
                _listenerBuffer.AddRange(listenerEntity.GetAnyEventNamespacedAddedListener().Value);
                foreach (var listener in _listenerBuffer)
                {
                    listener.OnAnyEventNamespacedAdded(entity, component.Value);
                }
            }
        }
    }
}
}
