//HintName: MyFeature.UniqueOneFieldNamespacedComponent.MyApp.Main.ContextExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ContextExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable disable

using global::MyApp.Main;
using static global::MyFeature.MyAppMainUniqueOneFieldNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainUniqueOneFieldNamespacedContextExtension
{
    public static bool HasUniqueOneFieldNamespaced(this MyApp.MainContext context, string value)
    {
        return context.GetUniqueOneFieldNamespacedEntity() != null;
    }

    public static Entity SetUniqueOneFieldNamespaced(this MyApp.MainContext context, string value)
    {
        var entity = context.GetUniqueOneFieldNamespacedEntity();
        if (entity == null)
            entity = context.CreateEntity().AddUniqueOneFieldNamespaced(value);
        else
            entity.ReplaceUniqueOneFieldNamespaced(value);

        return entity;
    }

    public static void UnsetUniqueOneFieldNamespaced(this MyApp.MainContext context)
    {
        context.GetUniqueOneFieldNamespacedEntity()?.Destroy();
    }

    public static Entity GetUniqueOneFieldNamespacedEntity(this MyApp.MainContext context)
    {
        return context.GetGroup(Matcher.AllOf(Index)).GetSingleEntity();
    }
}
}
