//HintName: MyAppMainFlagEventRemovedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public interface IMyAppMainFlagEventRemovedListener
{
    void OnFlagEventRemoved(global::MyApp.Main.Entity entity);
}

public sealed class MyAppMainFlagEventRemovedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainFlagEventRemovedListener> Value;
}

public static class MyAppMainFlagEventRemovedListenerEventEntityExtension
{
    public static global::MyApp.Main.Entity AddFlagEventRemovedListener(this global::MyApp.Main.Entity entity, IMyAppMainFlagEventRemovedListener value)
    {
        var listeners = entity.HasFlagEventRemovedListener()
            ? entity.GetFlagEventRemovedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainFlagEventRemovedListener>();
        listeners.Add(value);
        return entity.ReplaceFlagEventRemovedListener(listeners);
    }

    public static void RemoveFlagEventRemovedListener(this global::MyApp.Main.Entity entity, IMyAppMainFlagEventRemovedListener value, bool removeListenerWhenEmpty = true)
    {
        var listeners = entity.GetFlagEventRemovedListener().Value;
        listeners.Remove(value);
        if (removeListenerWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveFlagEventRemovedListener();
            if (entity.IsEmpty())
                entity.Destroy();
        }
        else
        {
            entity.ReplaceFlagEventRemovedListener(listeners);
        }
    }
}

public sealed class MyAppMainFlagEventRemovedEventSystem : global::Entitas.ReactiveSystem<global::MyApp.Main.Entity>
{
    readonly global::System.Collections.Generic.List<IMyAppMainFlagEventRemovedListener> _listenerBuffer;

    public MyAppMainFlagEventRemovedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainFlagEventRemovedListener>();
    }

    protected override global::Entitas.ICollector<global::MyApp.Main.Entity> GetTrigger(global::Entitas.IContext<global::MyApp.Main.Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Added(MyAppMainFlagEventMatcher.FlagEvent)
        );
    }

    protected override bool Filter(global::MyApp.Main.Entity entity)
    {
        return !entity.HasFlagEvent() && entity.HasFlagEventRemovedListener();
    }

    protected override void Execute(global::System.Collections.Generic.List<global::MyApp.Main.Entity> entities)
    {
        foreach (var entity in entities)
        {
            _listenerBuffer.Clear();
            _listenerBuffer.AddRange(entity.GetFlagEventRemovedListener().Value);
            foreach (var listener in _listenerBuffer)
            {
                listener.OnFlagEventRemoved(entity);
            }
        }
    }
}
