//HintName: MyFeature.MyAppMainMultipleFieldsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainMultipleFieldsNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainMultipleFieldsNamespacedEntityExtension
{
    public static bool HasMultipleFieldsNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddMultipleFieldsNamespaced(this Entity entity, string value1, string value2, string value3)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleFieldsNamespacedComponent)componentPool.Pop()
            : new MultipleFieldsNamespacedComponent();
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceMultipleFieldsNamespaced(this Entity entity, string value1, string value2, string value3)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleFieldsNamespacedComponent)componentPool.Pop()
            : new MultipleFieldsNamespacedComponent();
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveMultipleFieldsNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MultipleFieldsNamespacedComponent GetMultipleFieldsNamespaced(this Entity entity)
    {
        return (MultipleFieldsNamespacedComponent)entity.GetComponent(Index.Value);
    }
}
}
