//HintName: MyFeature.MyAppMainUniqueNamespacedContextExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ContextExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyFeature
{
public static class MyAppMainUniqueNamespacedContextExtension
{
    public static bool HasUniqueNamespaced(this global::MyApp.MainContext context)
    {
        return context.GetUniqueNamespacedEntity() != null;
    }

    public static global::MyApp.Main.Entity SetUniqueNamespaced(this global::MyApp.MainContext context)
    {
        return context.GetUniqueNamespacedEntity() ?? context.CreateEntity().AddUniqueNamespaced();
    }

    public static void UnsetUniqueNamespaced(this global::MyApp.MainContext context)
    {
        context.GetUniqueNamespacedEntity()?.Destroy();
    }

    public static global::MyApp.Main.Entity GetUniqueNamespacedEntity(this global::MyApp.MainContext context)
    {
        return context.GetGroup(MyAppMainUniqueNamespacedMatcher.UniqueNamespaced).GetSingleEntity();
    }
}
}
