//HintName: MyApp.ContextInitialization.Initialize.ContextInitialization.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ContextInitializationMethod
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Library;

namespace MyApp
{
public static partial class ContextInitialization
{
    public static partial void Initialize()
    {
        global::MyFeature.MyAppLibraryContextFromDifferentAssemblyNamespacedComponentIndex.Index = new ComponentIndex(0);
        global::MyOtherFeature.MyAppLibraryCollisionComponentIndex.Index = new ComponentIndex(1);
        global::MyOtherFeature.MyAppLibraryHealthComponentIndex.Index = new ComponentIndex(2);
        global::MyOtherFeature.MyAppLibraryCollisionAddedListenerComponentIndex.Index = new ComponentIndex(3);

        global::MyApp.LibraryContext.ComponentNames = new string[]
        {
            "MyFeature.ContextFromDifferentAssemblyNamespaced",
            "MyOtherFeature.Collision",
            "MyOtherFeature.Health",
            "MyOtherFeature.MyAppLibraryCollisionAddedListener"
        };

        global::MyApp.LibraryContext.ComponentTypes = new global::System.Type[]
        {
            typeof(global::MyFeature.ContextFromDifferentAssemblyNamespacedComponent),
            typeof(global::MyOtherFeature.CollisionComponent),
            typeof(global::MyOtherFeature.HealthComponent),
            typeof(global::MyOtherFeature.MyAppLibraryCollisionAddedListenerComponent)
        };
    }
}
}
