//HintName: MyFeature.UniqueNamespacedComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using global::MyApp.Main;
using static global::MyFeature.MyAppMainUniqueNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainUniqueNamespacedEntityExtension
{
    static readonly UniqueNamespacedComponent SingleUniqueNamespacedComponent = new UniqueNamespacedComponent();

    public static Entity SetUniqueNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleUniqueNamespacedComponent);
        return entity;
    }

    public static Entity UnsetUniqueNamespaced(this Entity entity)
    {
        if (entity.HasComponent(Index.Value))
            entity.RemoveComponent(Index.Value);

        return entity;
    }

    public static UniqueNamespacedComponent? GetUniqueNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value)
            ? (UniqueNamespacedComponent)entity.GetComponent(Index.Value)
            : null;
    }
}
}
