//HintName: MyFeature.ContextFromDifferentAssemblyNamespacedComponent.MyApp.Library.ContextAttribute.ComponentIndex.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ComponentIndex
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using MyApp.Library.ContextAttribute;

namespace MyFeature
{
public static class MyAppLibraryContextAttributeContextFromDifferentAssemblyNamespacedComponentIndex
{
    public static ComponentIndex Index;
}
}
