//HintName: MyApp.Main.OneContextEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp.Main
{
public static class OneContextEntityExtension
{
    static readonly OneContextComponent SingleOneContextComponent = new OneContextComponent();

    public static bool HasOneContext(this MyApp.Main.Entity entity)
    {
        return entity.HasComponent(OneContextComponentIndex.Value);
    }

    public static MyApp.Main.Entity AddOneContext(this MyApp.Main.Entity entity)
    {
        entity.AddComponent(OneContextComponentIndex.Value, SingleOneContextComponent);
        return entity;
    }

    public static MyApp.Main.Entity ReplaceOneContext(this MyApp.Main.Entity entity)
    {
        entity.ReplaceComponent(OneContextComponentIndex.Value, SingleOneContextComponent);
        return entity;
    }

    public static MyApp.Main.Entity RemoveOneContext(this MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(OneContextComponentIndex.Value);
        return entity;
    }
}
}
