//HintName: MyApp.MainContext.EventSystemsExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EventSystemsContextExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

namespace MyApp
{
public static class MainContextEventSystemsExtension
{
    public static global::Entitas.Systems CreateEventSystems(this MainContext context)
    {
        var systems = new global::Entitas.Systems();
        systems.Add(new MyAppMainAnyEventAddedEventSystem(context)); // order: 1
        systems.Add(new MyAppMainAnyFlagEventAddedEventSystem(context)); // order: 1
        systems.Add(new MyFeature.MyAppMainAnyEventNamespacedAddedEventSystem(context)); // order: 1
        systems.Add(new MyFeature.MyAppMainAnyFlagEventNamespacedAddedEventSystem(context)); // order: 1
        systems.Add(new MyAppMainAnyEventRemovedEventSystem(context)); // order: 2
        systems.Add(new MyAppMainAnyFlagEventRemovedEventSystem(context)); // order: 2
        systems.Add(new MyFeature.MyAppMainAnyEventNamespacedRemovedEventSystem(context)); // order: 2
        systems.Add(new MyFeature.MyAppMainAnyFlagEventNamespacedRemovedEventSystem(context)); // order: 2
        systems.Add(new MyAppMainEventAddedEventSystem(context)); // order: 3
        systems.Add(new MyAppMainFlagEventAddedEventSystem(context)); // order: 3
        systems.Add(new MyFeature.MyAppMainEventNamespacedAddedEventSystem(context)); // order: 3
        systems.Add(new MyFeature.MyAppMainFlagEventNamespacedAddedEventSystem(context)); // order: 3
        systems.Add(new MyAppMainEventRemovedEventSystem(context)); // order: 4
        systems.Add(new MyAppMainFlagEventRemovedEventSystem(context)); // order: 4
        systems.Add(new MyFeature.MyAppMainEventNamespacedRemovedEventSystem(context)); // order: 4
        systems.Add(new MyFeature.MyAppMainFlagEventNamespacedRemovedEventSystem(context)); // order: 4
        return systems;
    }
}
}
