//HintName: MyFeature.MyAppMainEventNamespacedAddedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyFeature
{
public interface IMyAppMainEventNamespacedAddedListener
{
    void OnEventNamespacedAdded(global::MyApp.Main.Entity entity, string value);
}

public sealed class MyAppMainEventNamespacedAddedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainEventNamespacedAddedListener> Value;
}

public static class MyAppMainEventNamespacedAddedListenerEventEntityExtension
{
    public static global::MyApp.Main.Entity AddEventNamespacedAddedListener(this global::MyApp.Main.Entity entity, IMyAppMainEventNamespacedAddedListener value)
    {
        var listeners = entity.HasEventNamespacedAddedListener()
            ? entity.GetEventNamespacedAddedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainEventNamespacedAddedListener>();
        listeners.Add(value);
        return entity.ReplaceEventNamespacedAddedListener(listeners);
    }

    public static void RemoveEventNamespacedAddedListener(this global::MyApp.Main.Entity entity, IMyAppMainEventNamespacedAddedListener value, bool removeListenerWhenEmpty = true)
    {
        var listeners = entity.GetEventNamespacedAddedListener().Value;
        listeners.Remove(value);
        if (removeListenerWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveEventNamespacedAddedListener();
            if (entity.IsEmpty())
                entity.Destroy();
        }
        else
        {
            entity.ReplaceEventNamespacedAddedListener(listeners);
        }
    }
}

public sealed class MyAppMainEventNamespacedAddedEventSystem : global::Entitas.ReactiveSystem<global::MyApp.Main.Entity>
{
    readonly global::System.Collections.Generic.List<IMyAppMainEventNamespacedAddedListener> _listenerBuffer;

    public MyAppMainEventNamespacedAddedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainEventNamespacedAddedListener>();
    }

    protected override global::Entitas.ICollector<global::MyApp.Main.Entity> GetTrigger(global::Entitas.IContext<global::MyApp.Main.Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Added(MyAppMainEventNamespacedMatcher.EventNamespaced)
        );
    }

    protected override bool Filter(global::MyApp.Main.Entity entity)
    {
        return entity.HasEventNamespaced() && entity.HasEventNamespacedAddedListener();
    }

    protected override void Execute(global::System.Collections.Generic.List<global::MyApp.Main.Entity> entities)
    {
        foreach (var entity in entities)
        {
            var component = entity.GetEventNamespaced();
            _listenerBuffer.Clear();
            _listenerBuffer.AddRange(entity.GetEventNamespacedAddedListener().Value);
            foreach (var listener in _listenerBuffer)
            {
                listener.OnEventNamespacedAdded(entity, component.Value);
            }
        }
    }
}
}
