//HintName: MyApp.Main.ComponentsLookup.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ComponentsLookup
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp.Main
{
public static class ComponentsLookup
{
    public static void AssignComponentIndexes()
    {
        MyFeatureMultiplePropertiesNamespacedComponentIndex.Index = new ComponentIndex(0);
    }

    public static readonly string[] ComponentNames = new string[]
    {
        "MyFeatureMultiplePropertiesNamespaced"
    };

    public static readonly System.Type[] ComponentTypes = new System.Type[]
    {
        typeof(MyFeature.MultiplePropertiesNamespacedComponent)
    };
}
}
