//HintName: RemoveMyAppMainCleanupRemoveCleanupSystem.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.CleanupSystem
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed class RemoveMyAppMainCleanupRemoveCleanupSystem : global::Entitas.ICleanupSystem
{
    readonly global::Entitas.IGroup<global::MyApp.Main.Entity> _group;
    readonly global::System.Collections.Generic.List<global::MyApp.Main.Entity> _buffer = new global::System.Collections.Generic.List<global::MyApp.Main.Entity>();

    public RemoveMyAppMainCleanupRemoveCleanupSystem(global::MyApp.MainContext context)
    {
        _group = context.GetGroup(MyAppMainCleanupRemoveMatcher.CleanupRemove);
    }

    public void Cleanup()
    {
        foreach (var entity in _group.GetEntities(_buffer))
        {
            entity.RemoveCleanupRemove();
        }
    }
}
