//HintName: MyApp.Main.MyFeatureSomeNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using static MyApp.Main.MyFeatureSomeNamespacedComponentIndex;

namespace MyApp.Main
{
public static class MyFeatureSomeNamespacedEntityExtension
{
    static readonly MyFeature.SomeNamespacedComponent SingleSomeNamespacedComponent = new MyFeature.SomeNamespacedComponent();

    public static bool HasSomeNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddSomeNamespaced(this Entity entity)
    {
        entity.AddComponent(Index.Value, SingleSomeNamespacedComponent);
        return entity;
    }

    public static Entity ReplaceSomeNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleSomeNamespacedComponent);
        return entity;
    }

    public static Entity RemoveSomeNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MyFeature.SomeNamespacedComponent GetSomeNamespaced(this Entity entity)
    {
        return (MyFeature.SomeNamespacedComponent)entity.GetComponent(Index.Value);
    }
}
}
