//HintName: MyApp.Main.EntitasGeneratorsTestsFixturesComponentsMultipleFieldsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp.Main
{
public static class EntitasGeneratorsTestsFixturesComponentsMultipleFieldsNamespacedEntityExtension
{
    public static bool HasMultipleFieldsNamespaced(this MyApp.Main.Entity entity)
    {
        return entity.HasComponent(EntitasGeneratorsTestsFixturesComponentsMultipleFieldsNamespacedComponentIndex.Value);
    }

    public static MyApp.Main.Entity AddMultipleFieldsNamespaced(this MyApp.Main.Entity entity, string value1, string value2, string value3)
    {
        var index = EntitasGeneratorsTestsFixturesComponentsMultipleFieldsNamespacedComponentIndex.Value;
        var component = (Entitas.Generators.Tests.Fixtures.Components.MultipleFieldsNamespacedComponent)entity.CreateComponent(index, typeof(Entitas.Generators.Tests.Fixtures.Components.MultipleFieldsNamespacedComponent));
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.AddComponent(index, component);
        return entity;
    }

    public static MyApp.Main.Entity ReplaceMultipleFieldsNamespaced(this MyApp.Main.Entity entity, string value1, string value2, string value3)
    {
        var index = EntitasGeneratorsTestsFixturesComponentsMultipleFieldsNamespacedComponentIndex.Value;
        var component = (Entitas.Generators.Tests.Fixtures.Components.MultipleFieldsNamespacedComponent)entity.CreateComponent(index, typeof(Entitas.Generators.Tests.Fixtures.Components.MultipleFieldsNamespacedComponent));
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static MyApp.Main.Entity RemoveMultipleFieldsNamespaced(this MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(EntitasGeneratorsTestsFixturesComponentsMultipleFieldsNamespacedComponentIndex.Value);
        return entity;
    }
}
}
