//HintName: Other.OneContextEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Other
{
public static class OneContextEntityExtension
{
    static readonly OneContextComponent SingleOneContextComponent = new OneContextComponent();

    public static bool HasOneContext(this Other.Entity entity)
    {
        return entity.HasComponent(OneContextComponentIndex.Value);
    }

    public static Other.Entity AddOneContext(this Other.Entity entity)
    {
        entity.AddComponent(OneContextComponentIndex.Value, SingleOneContextComponent);
        return entity;
    }

    public static Other.Entity ReplaceOneContext(this Other.Entity entity)
    {
        entity.ReplaceComponent(OneContextComponentIndex.Value, SingleOneContextComponent);
        return entity;
    }

    public static Other.Entity RemoveOneContext(this Other.Entity entity)
    {
        entity.RemoveComponent(OneContextComponentIndex.Value);
        return entity;
    }
}
}
