//HintName: MyApp.Main.ContextInitializationMethod.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ContextInitializationMethod
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

namespace MyApp
{
public static partial class ContextInitialization
{
    public static partial void Initialize()
    {
        global::MyFeature.MyAppMainAnotherNamespacedComponentIndex.Index = new ComponentIndex(0);
        global::MyFeature.MyAppMainSomeNamespacedComponentIndex.Index = new ComponentIndex(1);

        MyApp.MainContext.ComponentNames = new string[]
        {
            "MyFeature.AnotherNamespaced",
            "MyFeature.SomeNamespaced"
        };

        MyApp.MainContext.ComponentTypes = new global::System.Type[]
        {
            typeof(global::MyFeature.AnotherNamespacedComponent),
            typeof(global::MyFeature.SomeNamespacedComponent)
        };
    }
}
}
