//HintName: MyAppMainAnyEventRemovedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public interface IMyAppMainAnyEventRemovedListener
{
    void OnAnyEventRemoved(global::MyApp.Main.Entity entity);
}

public sealed class MyAppMainAnyEventRemovedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainAnyEventRemovedListener> Value;
}

public static class MyAppMainAnyEventRemovedListenerEventEntityExtension
{
    public static global::MyApp.Main.Entity AddAnyEventRemovedListener(this global::MyApp.Main.Entity entity, IMyAppMainAnyEventRemovedListener value)
    {
        var listeners = entity.HasAnyEventRemovedListener()
            ? entity.GetAnyEventRemovedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainAnyEventRemovedListener>();
        listeners.Add(value);
        return entity.ReplaceAnyEventRemovedListener(listeners);
    }

    public static void RemoveAnyEventRemovedListener(this global::MyApp.Main.Entity entity, IMyAppMainAnyEventRemovedListener value, bool removeListenerWhenEmpty = true)
    {
        var listeners = entity.GetAnyEventRemovedListener().Value;
        listeners.Remove(value);
        if (removeListenerWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveAnyEventRemovedListener();
            if (entity.IsEmpty())
                entity.Destroy();
        }
        else
        {
            entity.ReplaceAnyEventRemovedListener(listeners);
        }
    }
}

public sealed class MyAppMainAnyEventRemovedEventSystem : global::Entitas.ReactiveSystem<global::MyApp.Main.Entity>
{
    readonly global::Entitas.IGroup<global::MyApp.Main.Entity> _listeners;
    readonly global::System.Collections.Generic.List<global::MyApp.Main.Entity> _entityBuffer;
    readonly global::System.Collections.Generic.List<IMyAppMainAnyEventRemovedListener> _listenerBuffer;

    public MyAppMainAnyEventRemovedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listeners = context.GetGroup(MyAppMainAnyEventRemovedListenerMatcher.AnyEventRemovedListener);
        _entityBuffer = new global::System.Collections.Generic.List<global::MyApp.Main.Entity>();
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainAnyEventRemovedListener>();
    }

    protected override global::Entitas.ICollector<global::MyApp.Main.Entity> GetTrigger(global::Entitas.IContext<global::MyApp.Main.Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Removed(MyAppMainEventMatcher.Event)
        );
    }

    protected override bool Filter(global::MyApp.Main.Entity entity)
    {
        return !entity.HasEvent();
    }

    protected override void Execute(global::System.Collections.Generic.List<global::MyApp.Main.Entity> entities)
    {
        foreach (var entity in entities)
        {
            foreach (var listenerEntity in _listeners.GetEntities(_entityBuffer))
            {
                _listenerBuffer.Clear();
                _listenerBuffer.AddRange(listenerEntity.GetAnyEventRemovedListener().Value);
                foreach (var listener in _listenerBuffer)
                {
                    listener.OnAnyEventRemoved(entity);
                }
            }
        }
    }
}
