//HintName: MyFeature.ContextFromDifferentAssemblyNamespacedComponent.MyApp.Library.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using global::MyApp.Library;
using static global::MyFeature.MyAppLibraryContextFromDifferentAssemblyNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppLibraryContextFromDifferentAssemblyNamespacedEntityExtension
{
    static readonly ContextFromDifferentAssemblyNamespacedComponent SingleContextFromDifferentAssemblyNamespacedComponent = new ContextFromDifferentAssemblyNamespacedComponent();

    public static Entity SetContextFromDifferentAssemblyNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleContextFromDifferentAssemblyNamespacedComponent);
        return entity;
    }

    public static Entity UnsetContextFromDifferentAssemblyNamespaced(this Entity entity)
    {
        if (entity.HasComponent(Index.Value))
            entity.RemoveComponent(Index.Value);

        return entity;
    }

    public static ContextFromDifferentAssemblyNamespacedComponent? GetContextFromDifferentAssemblyNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value)
            ? (ContextFromDifferentAssemblyNamespacedComponent)entity.GetComponent(Index.Value)
            : null;
    }
}
}
