//HintName: MyFeature.MyAppMainEventNamespacedAddedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

namespace MyFeature
{
public interface IMyAppMainEventNamespacedAddedListener
{
    void OnEventNamespacedAdded(Entity entity, string value);
}

public sealed class MyAppMainEventNamespacedAddedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainEventNamespacedAddedListener> Value;
}

public static class MyAppMainEventNamespacedAddedListenerEventEntityExtension
{
    public static void AddEventNamespacedAddedListener(this Entity entity, IMyAppMainEventNamespacedAddedListener value)
    {
        var listeners = entity.HasEventNamespacedAddedListener()
            ? entity.GetEventNamespacedAddedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainEventNamespacedAddedListener>();
        listeners.Add(value);
        entity.ReplaceEventNamespacedAddedListener(listeners);
    }

    public static void RemoveEventNamespacedAddedListener(this Entity entity, IMyAppMainEventNamespacedAddedListener value, bool removeComponentWhenEmpty = true)
    {
        var listeners = entity.GetEventNamespacedAddedListener().Value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveEventNamespacedAddedListener();
        }
        else
        {
            entity.ReplaceEventNamespacedAddedListener(listeners);
        }
    }
}}
