//HintName: Other.OneFieldEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Other
{
public static class OneFieldEntityExtension
{
    public static bool HasOneField(this Other.Entity entity)
    {
        return entity.HasComponent(OneFieldComponentIndex.Value);
    }

    public static Other.Entity AddOneField(this Other.Entity entity, string value)
    {
        var index = OneFieldComponentIndex.Value;
        var component = (OneFieldComponent)entity.CreateComponent(index, typeof(OneFieldComponent));
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Other.Entity ReplaceOneField(this Other.Entity entity, string value)
    {
        var index = OneFieldComponentIndex.Value;
        var component = (OneFieldComponent)entity.CreateComponent(index, typeof(OneFieldComponent));
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Other.Entity RemoveOneField(this Other.Entity entity)
    {
        entity.RemoveComponent(OneFieldComponentIndex.Value);
        return entity;
    }
}
}
