//HintName: MyApp.MainContextEntityIndexExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityIndexExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp
{
public static class MainContextEntityIndexExtension
{
    public const string EntityIndexValue = "EntityIndexValue";
    public const string MyFeatureEntityIndexNamespacedValue = "MyFeatureEntityIndexNamespacedValue";
    public const string MyFeaturePrimaryEntityIndexNamespacedValue = "MyFeaturePrimaryEntityIndexNamespacedValue";
    public const string PrimaryEntityIndexValue = "PrimaryEntityIndexValue";

    public static MainContext AddEntityIndexes(this MainContext context)
    {
        context.AddEntityIndex(new global::Entitas.EntityIndex<global::MyApp.Main.Entity, string>(
            EntityIndexValue,
            context.GetGroup(global::MyAppMainEntityIndexMatcher.EntityIndex),
            (entity, component) => ((global::EntityIndexComponent)component).Value));

        context.AddEntityIndex(new global::Entitas.EntityIndex<global::MyApp.Main.Entity, string>(
            MyFeatureEntityIndexNamespacedValue,
            context.GetGroup(global::MyFeature.MyAppMainEntityIndexNamespacedMatcher.EntityIndexNamespaced),
            (entity, component) => ((global::MyFeature.EntityIndexNamespacedComponent)component).Value));

        context.AddEntityIndex(new global::Entitas.PrimaryEntityIndex<global::MyApp.Main.Entity, string>(
            MyFeaturePrimaryEntityIndexNamespacedValue,
            context.GetGroup(global::MyFeature.MyAppMainPrimaryEntityIndexNamespacedMatcher.PrimaryEntityIndexNamespaced),
            (entity, component) => ((global::MyFeature.PrimaryEntityIndexNamespacedComponent)component).Value));

        context.AddEntityIndex(new global::Entitas.PrimaryEntityIndex<global::MyApp.Main.Entity, string>(
            PrimaryEntityIndexValue,
            context.GetGroup(global::MyAppMainPrimaryEntityIndexMatcher.PrimaryEntityIndex),
            (entity, component) => ((global::PrimaryEntityIndexComponent)component).Value));

        return context;
    }
}
}

public static class EntityIndexExtension
{
    public static global::System.Collections.Generic.HashSet<global::MyApp.Main.Entity> GetEntitiesWithEntityIndexValue(this global::MyApp.MainContext context, string value)
    {
        return ((global::Entitas.EntityIndex<global::MyApp.Main.Entity, string>)context.GetEntityIndex(global::MyApp.MainContextEntityIndexExtension.EntityIndexValue)).GetEntities(value);
    }

    public static global::MyApp.Main.Entity GetEntityWithPrimaryEntityIndexValue(this global::MyApp.MainContext context, string value)
    {
        return ((global::Entitas.PrimaryEntityIndex<global::MyApp.Main.Entity, string>)context.GetEntityIndex(global::MyApp.MainContextEntityIndexExtension.PrimaryEntityIndexValue)).GetEntity(value);
    }
}

namespace MyFeature
{
public static class EntityIndexExtension
{
    public static global::System.Collections.Generic.HashSet<global::MyApp.Main.Entity> GetEntitiesWithEntityIndexNamespacedValue(this global::MyApp.MainContext context, string value)
    {
        return ((global::Entitas.EntityIndex<global::MyApp.Main.Entity, string>)context.GetEntityIndex(global::MyApp.MainContextEntityIndexExtension.MyFeatureEntityIndexNamespacedValue)).GetEntities(value);
    }

    public static global::MyApp.Main.Entity GetEntityWithPrimaryEntityIndexNamespacedValue(this global::MyApp.MainContext context, string value)
    {
        return ((global::Entitas.PrimaryEntityIndex<global::MyApp.Main.Entity, string>)context.GetEntityIndex(global::MyApp.MainContextEntityIndexExtension.MyFeaturePrimaryEntityIndexNamespacedValue)).GetEntity(value);
    }
}
}
