//HintName: MyFeature.MyAppMainSomeNamespacedComponentIndex.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ComponentIndex
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyFeature
{
public static class MyAppMainSomeNamespacedComponentIndex
{
    public static global::MyApp.Main.ComponentIndex Index;
}
}
