//HintName: MyFeature.AnotherNamespacedComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using global::MyApp.Main;
using static global::MyFeature.MyAppMainAnotherNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainAnotherNamespacedEntityExtension
{
    static readonly AnotherNamespacedComponent SingleAnotherNamespacedComponent = new AnotherNamespacedComponent();

    public static Entity SetAnotherNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleAnotherNamespacedComponent);
        return entity;
    }

    public static Entity UnsetAnotherNamespaced(this Entity entity)
    {
        if (entity.HasComponent(Index.Value))
            entity.RemoveComponent(Index.Value);

        return entity;
    }

    public static AnotherNamespacedComponent? GetAnotherNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value)
            ? (AnotherNamespacedComponent)entity.GetComponent(Index.Value)
            : null;
    }
}
}
