//HintName: EmptyContextEventSystemsExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EventSystemsContextExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class EmptyContextEventSystemsExtension
{
    public static global::Entitas.Systems CreateEventSystems(this EmptyContext context)
    {
        return null;
    }
}
