//HintName: MyFeature.MultiplePropertiesNamespacedComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainMultiplePropertiesNamespacedComponentIndex;

namespace MyFeature
{
public static class MyAppMainMultiplePropertiesNamespacedEntityExtension
{
    public static bool HasMultiplePropertiesNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddMultiplePropertiesNamespaced(this Entity entity, string value1, string value2, string value3)
    {
        var index = Index.Value;
        var component = (MultiplePropertiesNamespacedComponent)entity.CreateComponent(index, typeof(MultiplePropertiesNamespacedComponent));
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceMultiplePropertiesNamespaced(this Entity entity, string value1, string value2, string value3)
    {
        var index = Index.Value;
        var component = (MultiplePropertiesNamespacedComponent)entity.CreateComponent(index, typeof(MultiplePropertiesNamespacedComponent));
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveMultiplePropertiesNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MultiplePropertiesNamespacedComponent GetMultiplePropertiesNamespaced(this Entity entity)
    {
        return (MultiplePropertiesNamespacedComponent)entity.GetComponent(Index.Value);
    }
}
}
