//HintName: MyAppMainEventRemovedListenerEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyAppMainEventRemovedListenerComponentIndex;

public static class MyAppMainEventRemovedListenerEntityExtension
{
    public static bool HasEventRemovedListener(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddEventRemovedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainEventRemovedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainEventRemovedListenerComponent)componentPool.Pop()
            : new MyAppMainEventRemovedListenerComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceEventRemovedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainEventRemovedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainEventRemovedListenerComponent)componentPool.Pop()
            : new MyAppMainEventRemovedListenerComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveEventRemovedListener(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MyAppMainEventRemovedListenerComponent GetEventRemovedListener(this Entity entity)
    {
        return (MyAppMainEventRemovedListenerComponent)entity.GetComponent(Index.Value);
    }
}
