//HintName: MyFeature.MyAppMainAnyEventNamespacedRemovedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

namespace MyFeature
{
public interface IMyAppMainAnyEventNamespacedRemovedListener
{
    void OnAnyEventNamespacedRemoved(Entity entity);
}

public sealed class MyAppMainAnyEventNamespacedRemovedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedRemovedListener> Value;
}

public static class MyAppMainAnyEventNamespacedRemovedListenerEventEntityExtension
{
    public static Entity AddAnyEventNamespacedRemovedListener(this Entity entity, IMyAppMainAnyEventNamespacedRemovedListener value)
    {
        var listeners = entity.HasAnyEventNamespacedRemovedListener()
            ? entity.GetAnyEventNamespacedRemovedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedRemovedListener>();
        listeners.Add(value);
        return entity.ReplaceAnyEventNamespacedRemovedListener(listeners);
    }

    public static void RemoveAnyEventNamespacedRemovedListener(this Entity entity, IMyAppMainAnyEventNamespacedRemovedListener value, bool removeListenerWhenEmpty = true)
    {
        var listeners = entity.GetAnyEventNamespacedRemovedListener().Value;
        listeners.Remove(value);
        if (removeListenerWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveAnyEventNamespacedRemovedListener();
            if (entity.IsEmpty())
                entity.Destroy();
        }
        else
        {
            entity.ReplaceAnyEventNamespacedRemovedListener(listeners);
        }
    }
}

public sealed class MyAppMainAnyEventNamespacedRemovedEventSystem : global::Entitas.ReactiveSystem<Entity>
{
    readonly global::Entitas.IGroup<Entity> _listeners;
    readonly global::System.Collections.Generic.List<Entity> _entityBuffer;
    readonly global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedRemovedListener> _listenerBuffer;

    public MyAppMainAnyEventNamespacedRemovedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listeners = context.GetGroup(MyAppMainAnyEventNamespacedRemovedListenerMatcher.AnyEventNamespacedRemovedListener);
        _entityBuffer = new global::System.Collections.Generic.List<Entity>();
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedRemovedListener>();
    }

    protected override global::Entitas.ICollector<Entity> GetTrigger(global::Entitas.IContext<Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Added(MyAppMainEventNamespacedMatcher.EventNamespaced)
        );
    }

    protected override bool Filter(Entity entity)
    {
        return !entity.HasEventNamespaced();
    }

    protected override void Execute(global::System.Collections.Generic.List<Entity> entities)
    {
        foreach (var entity in entities)
        {
            foreach (var listenerEntity in _listeners.GetEntities(_entityBuffer))
            {
                _listenerBuffer.Clear();
                _listenerBuffer.AddRange(listenerEntity.GetAnyEventNamespacedRemovedListener().Value);
                foreach (var listener in _listenerBuffer)
                {
                    listener.OnAnyEventNamespacedRemoved(entity);
                }
            }
        }
    }
}
}
