//HintName: MyAppMainFlagEventEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyAppMainFlagEventComponentIndex;

public static class MyAppMainFlagEventEntityExtension
{
    static readonly FlagEventComponent SingleFlagEventComponent = new FlagEventComponent();

    public static bool HasFlagEvent(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddFlagEvent(this Entity entity)
    {
        entity.AddComponent(Index.Value, SingleFlagEventComponent);
        return entity;
    }

    public static Entity ReplaceFlagEvent(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleFlagEventComponent);
        return entity;
    }

    public static Entity RemoveFlagEvent(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static FlagEventComponent GetFlagEvent(this Entity entity)
    {
        return (FlagEventComponent)entity.GetComponent(Index.Value);
    }
}
