//HintName: MyApp.Main.MyAppOneContextNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp.Main
{
public static class MyAppOneContextNamespacedEntityExtension
{
    static readonly MyApp.OneContextNamespacedComponent SingleOneContextNamespacedComponent = new MyApp.OneContextNamespacedComponent();

    public static bool HasOneContextNamespaced(this Entity entity)
    {
        return entity.HasComponent(MyAppOneContextNamespacedComponentIndex.Value);
    }

    public static Entity AddOneContextNamespaced(this Entity entity)
    {
        entity.AddComponent(MyAppOneContextNamespacedComponentIndex.Value, SingleOneContextNamespacedComponent);
        return entity;
    }

    public static Entity ReplaceOneContextNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(MyAppOneContextNamespacedComponentIndex.Value, SingleOneContextNamespacedComponent);
        return entity;
    }

    public static Entity RemoveOneContextNamespaced(this Entity entity)
    {
        entity.RemoveComponent(MyAppOneContextNamespacedComponentIndex.Value);
        return entity;
    }
}
}
