//HintName: MyFeature.MyAppMainAnyEventNamespacedAddedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

namespace MyFeature
{
public interface IMyAppMainAnyEventNamespacedAddedListener
{
    void OnAnyEventNamespacedAdded(Entity entity, string value);
}

public sealed class MyAppMainAnyEventNamespacedAddedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedAddedListener> Value;
}

public static class MyAppMainAnyEventNamespacedAddedListenerEventEntityExtension
{
    public static Entity AddAnyEventNamespacedAddedListener(this Entity entity, IMyAppMainAnyEventNamespacedAddedListener value)
    {
        var listeners = entity.HasAnyEventNamespacedAddedListener()
            ? entity.GetAnyEventNamespacedAddedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedAddedListener>();
        listeners.Add(value);
        return entity.ReplaceAnyEventNamespacedAddedListener(listeners);
    }

    public static void RemoveAnyEventNamespacedAddedListener(this Entity entity, IMyAppMainAnyEventNamespacedAddedListener value, bool destroyListenerWhenEmpty = true)
    {
        var listeners = entity.GetAnyEventNamespacedAddedListener().Value;
        listeners.Remove(value);
        if (destroyListenerWhenEmpty && listeners.Count == 0)
            entity.Destroy();
        else
            entity.ReplaceAnyEventNamespacedAddedListener(listeners);
    }
}

public sealed class MyAppMainAnyEventNamespacedAddedEventSystem : global::Entitas.ReactiveSystem<Entity>
{
    readonly global::Entitas.IGroup<Entity> _listeners;
    readonly global::System.Collections.Generic.List<Entity> _entityBuffer;
    readonly global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedAddedListener> _listenerBuffer;

    public MyAppMainAnyEventNamespacedAddedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listeners = context.GetGroup(MyAppMainAnyEventNamespacedAddedListenerMatcher.AnyEventNamespacedAddedListener);
        _entityBuffer = new global::System.Collections.Generic.List<Entity>();
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedAddedListener>();
    }

    protected override global::Entitas.ICollector<Entity> GetTrigger(global::Entitas.IContext<Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Added(MyAppMainEventNamespacedMatcher.EventNamespaced)
        );
    }

    protected override bool Filter(Entity entity)
    {
        return entity.HasEventNamespaced();
    }

    protected override void Execute(global::System.Collections.Generic.List<Entity> entities)
    {
        foreach (var entity in entities)
        {
            var component = entity.GetEventNamespaced();
            foreach (var listenerEntity in _listeners.GetEntities(_entityBuffer))
            {
                _listenerBuffer.Clear();
                _listenerBuffer.AddRange(listenerEntity.GetAnyEventNamespacedAddedListener().Value);
                foreach (var listener in _listenerBuffer)
                {
                    listener.OnAnyEventNamespacedAdded(entity, component.Value);
                }
            }
        }
    }
}
}
