//HintName: MyApp.Main.EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp.Main
{
public static class EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedEntityExtension
{
    static readonly Entitas.Generators.Tests.Fixtures.Components.OneContextNamespacedComponent SingleOneContextNamespacedComponent = new Entitas.Generators.Tests.Fixtures.Components.OneContextNamespacedComponent();

    public static bool HasOneContextNamespaced(this MyApp.Main.Entity entity)
    {
        return entity.HasComponent(EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedComponentIndex.Value);
    }

    public static MyApp.Main.Entity AddOneContextNamespaced(this MyApp.Main.Entity entity)
    {
        entity.AddComponent(EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedComponentIndex.Value, SingleOneContextNamespacedComponent);
        return entity;
    }

    public static MyApp.Main.Entity ReplaceOneContextNamespaced(this MyApp.Main.Entity entity)
    {
        entity.ReplaceComponent(EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedComponentIndex.Value, SingleOneContextNamespacedComponent);
        return entity;
    }

    public static MyApp.Main.Entity RemoveOneContextNamespaced(this MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(EntitasGeneratorsTestsFixturesComponentsOneContextNamespacedComponentIndex.Value);
        return entity;
    }
}
}
