//HintName: Other.MyAppSomeNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Other
{
public static class MyAppSomeNamespacedEntityExtension
{
    static readonly MyApp.SomeNamespacedComponent SingleSomeNamespacedComponent = new MyApp.SomeNamespacedComponent();

    public static bool HasSomeNamespaced(this Entity entity)
    {
        return entity.HasComponent(MyAppSomeNamespacedComponentIndex.Value);
    }

    public static Entity AddSomeNamespaced(this Entity entity)
    {
        entity.AddComponent(MyAppSomeNamespacedComponentIndex.Value, SingleSomeNamespacedComponent);
        return entity;
    }

    public static Entity ReplaceSomeNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(MyAppSomeNamespacedComponentIndex.Value, SingleSomeNamespacedComponent);
        return entity;
    }

    public static Entity RemoveSomeNamespaced(this Entity entity)
    {
        entity.RemoveComponent(MyAppSomeNamespacedComponentIndex.Value);
        return entity;
    }
}
}
