//HintName: MyApp.Main.EntitasGeneratorsTestsFixturesComponentsReservedKeywordFieldsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp.Main
{
public static class EntitasGeneratorsTestsFixturesComponentsReservedKeywordFieldsNamespacedEntityExtension
{
    public static bool HasReservedKeywordFieldsNamespaced(this MyApp.Main.Entity entity)
    {
        return entity.HasComponent(EntitasGeneratorsTestsFixturesComponentsReservedKeywordFieldsNamespacedComponentIndex.Value);
    }

    public static MyApp.Main.Entity AddReservedKeywordFieldsNamespaced(this MyApp.Main.Entity entity, string @namespace, string @class, string @public)
    {
        var index = EntitasGeneratorsTestsFixturesComponentsReservedKeywordFieldsNamespacedComponentIndex.Value;
        var component = (Entitas.Generators.Tests.Fixtures.Components.ReservedKeywordFieldsNamespacedComponent)entity.CreateComponent(index, typeof(Entitas.Generators.Tests.Fixtures.Components.ReservedKeywordFieldsNamespacedComponent));
        component.Namespace = @namespace;
        component.Class = @class;
        component.Public = @public;
        entity.AddComponent(index, component);
        return entity;
    }

    public static MyApp.Main.Entity ReplaceReservedKeywordFieldsNamespaced(this MyApp.Main.Entity entity, string @namespace, string @class, string @public)
    {
        var index = EntitasGeneratorsTestsFixturesComponentsReservedKeywordFieldsNamespacedComponentIndex.Value;
        var component = (Entitas.Generators.Tests.Fixtures.Components.ReservedKeywordFieldsNamespacedComponent)entity.CreateComponent(index, typeof(Entitas.Generators.Tests.Fixtures.Components.ReservedKeywordFieldsNamespacedComponent));
        component.Namespace = @namespace;
        component.Class = @class;
        component.Public = @public;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static MyApp.Main.Entity RemoveReservedKeywordFieldsNamespaced(this MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(EntitasGeneratorsTestsFixturesComponentsReservedKeywordFieldsNamespacedComponentIndex.Value);
        return entity;
    }
}
}
