//HintName: MyAppMainSomeEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class MyAppMainSomeEntityExtension
{
    static readonly SomeComponent SingleSomeComponent = new SomeComponent();

    public static bool HasSome(this global::MyApp.Main.Entity entity)
    {
        return entity.HasComponent(MyAppMainSomeComponentIndex.Index.Value);
    }

    public static global::MyApp.Main.Entity AddSome(this global::MyApp.Main.Entity entity)
    {
        entity.AddComponent(MyAppMainSomeComponentIndex.Index.Value, SingleSomeComponent);
        return entity;
    }

    public static global::MyApp.Main.Entity ReplaceSome(this global::MyApp.Main.Entity entity)
    {
        entity.ReplaceComponent(MyAppMainSomeComponentIndex.Index.Value, SingleSomeComponent);
        return entity;
    }

    public static global::MyApp.Main.Entity RemoveSome(this global::MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(MyAppMainSomeComponentIndex.Index.Value);
        return entity;
    }

    public static SomeComponent GetSome(this global::MyApp.Main.Entity entity)
    {
        return (SomeComponent)entity.GetComponent(MyAppMainSomeComponentIndex.Index.Value);
    }
}
