//HintName: MyFeature.MyAppMainAnyEventNamespacedAddedListenerEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainAnyEventNamespacedAddedListenerComponentIndex;

namespace MyFeature
{
public static class MyAppMainAnyEventNamespacedAddedListenerEntityExtension
{
    public static bool HasAnyEventNamespacedAddedListener(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddAnyEventNamespacedAddedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainAnyEventNamespacedAddedListenerComponent)componentPool.Pop()
            : new MyAppMainAnyEventNamespacedAddedListenerComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceAnyEventNamespacedAddedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainAnyEventNamespacedAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainAnyEventNamespacedAddedListenerComponent)componentPool.Pop()
            : new MyAppMainAnyEventNamespacedAddedListenerComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveAnyEventNamespacedAddedListener(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MyAppMainAnyEventNamespacedAddedListenerComponent GetAnyEventNamespacedAddedListener(this Entity entity)
    {
        return (MyAppMainAnyEventNamespacedAddedListenerComponent)entity.GetComponent(Index.Value);
    }
}
}
