//HintName: MyApp.Main.MyFeatureMultipleFieldsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp.Main
{
public static class MyFeatureMultipleFieldsNamespacedEntityExtension
{
    public static MyFeature.MultipleFieldsNamespacedComponent GetMultipleFieldsNamespaced(this Entity entity)
    {
        return (MyFeature.MultipleFieldsNamespacedComponent)entity.GetComponent(MyFeatureMultipleFieldsNamespacedComponentIndex.Value);
    }

    public static void Deconstruct(this MyFeature.MultipleFieldsNamespacedComponent component, out string value1, out string value2, out string value3)
    {
        value1 = component.Value1;
        value2 = component.Value2;
        value3 = component.Value3;
    }

    public static bool HasMultipleFieldsNamespaced(this Entity entity)
    {
        return entity.HasComponent(MyFeatureMultipleFieldsNamespacedComponentIndex.Value);
    }

    public static Entity AddMultipleFieldsNamespaced(this Entity entity, string value1, string value2, string value3)
    {
        var index = MyFeatureMultipleFieldsNamespacedComponentIndex.Value;
        var component = (MyFeature.MultipleFieldsNamespacedComponent)entity.CreateComponent(index, typeof(MyFeature.MultipleFieldsNamespacedComponent));
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceMultipleFieldsNamespaced(this Entity entity, string value1, string value2, string value3)
    {
        var index = MyFeatureMultipleFieldsNamespacedComponentIndex.Value;
        var component = (MyFeature.MultipleFieldsNamespacedComponent)entity.CreateComponent(index, typeof(MyFeature.MultipleFieldsNamespacedComponent));
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveMultipleFieldsNamespaced(this Entity entity)
    {
        entity.RemoveComponent(MyFeatureMultipleFieldsNamespacedComponentIndex.Value);
        return entity;
    }
}
}
