//HintName: SomeComponent.MyApp.Main.EntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using MyApp.Main;
using static MyAppMainSomeComponentIndex;

public static class MyAppMainSomeEntityExtension
{
    static readonly SomeComponent SingleSomeComponent = new SomeComponent();

    public static bool HasSome(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddSome(this Entity entity)
    {
        entity.AddComponent(Index.Value, SingleSomeComponent);
        return entity;
    }

    public static Entity ReplaceSome(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleSomeComponent);
        return entity;
    }

    public static Entity RemoveSome(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static SomeComponent GetSome(this Entity entity)
    {
        return (SomeComponent)entity.GetComponent(Index.Value);
    }
}
