//HintName: MyFeature.MyAppLibraryContextFromDifferentAssemblyNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyFeature
{
public static class MyAppLibraryContextFromDifferentAssemblyNamespacedEntityExtension
{
    static readonly ContextFromDifferentAssemblyNamespacedComponent SingleContextFromDifferentAssemblyNamespacedComponent = new ContextFromDifferentAssemblyNamespacedComponent();

    public static bool HasContextFromDifferentAssemblyNamespaced(this global::MyApp.Library.Entity entity)
    {
        return entity.HasComponent(MyAppLibraryContextFromDifferentAssemblyNamespacedComponentIndex.Index.Value);
    }

    public static global::MyApp.Library.Entity AddContextFromDifferentAssemblyNamespaced(this global::MyApp.Library.Entity entity)
    {
        entity.AddComponent(MyAppLibraryContextFromDifferentAssemblyNamespacedComponentIndex.Index.Value, SingleContextFromDifferentAssemblyNamespacedComponent);
        return entity;
    }

    public static global::MyApp.Library.Entity ReplaceContextFromDifferentAssemblyNamespaced(this global::MyApp.Library.Entity entity)
    {
        entity.ReplaceComponent(MyAppLibraryContextFromDifferentAssemblyNamespacedComponentIndex.Index.Value, SingleContextFromDifferentAssemblyNamespacedComponent);
        return entity;
    }

    public static global::MyApp.Library.Entity RemoveContextFromDifferentAssemblyNamespaced(this global::MyApp.Library.Entity entity)
    {
        entity.RemoveComponent(MyAppLibraryContextFromDifferentAssemblyNamespacedComponentIndex.Index.Value);
        return entity;
    }

    public static ContextFromDifferentAssemblyNamespacedComponent GetContextFromDifferentAssemblyNamespaced(this global::MyApp.Library.Entity entity)
    {
        return (ContextFromDifferentAssemblyNamespacedComponent)entity.GetComponent(MyAppLibraryContextFromDifferentAssemblyNamespacedComponentIndex.Index.Value);
    }
}
}
