//HintName: MyAppMainEventAddedListenerEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyAppMainEventAddedListenerComponentIndex;

public static class MyAppMainEventAddedListenerEntityExtension
{
    public static bool HasEventAddedListener(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddEventAddedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainEventAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainEventAddedListenerComponent)componentPool.Pop()
            : new MyAppMainEventAddedListenerComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceEventAddedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainEventAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainEventAddedListenerComponent)componentPool.Pop()
            : new MyAppMainEventAddedListenerComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveEventAddedListener(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MyAppMainEventAddedListenerComponent GetEventAddedListener(this Entity entity)
    {
        return (MyAppMainEventAddedListenerComponent)entity.GetComponent(Index.Value);
    }
}
