//HintName: MyFeature.MyAppMainMultipleFieldsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyFeature
{
public static class MyAppMainMultipleFieldsNamespacedEntityExtension
{
    public static bool HasMultipleFieldsNamespaced(this global::MyApp.Main.Entity entity)
    {
        return entity.HasComponent(MyAppMainMultipleFieldsNamespacedComponentIndex.Index.Value);
    }

    public static global::MyApp.Main.Entity AddMultipleFieldsNamespaced(this global::MyApp.Main.Entity entity, string value1, string value2, string value3)
    {
        var index = MyAppMainMultipleFieldsNamespacedComponentIndex.Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleFieldsNamespacedComponent)componentPool.Pop()
            : new MultipleFieldsNamespacedComponent();
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.AddComponent(index, component);
        return entity;
    }

    public static global::MyApp.Main.Entity ReplaceMultipleFieldsNamespaced(this global::MyApp.Main.Entity entity, string value1, string value2, string value3)
    {
        var index = MyAppMainMultipleFieldsNamespacedComponentIndex.Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleFieldsNamespacedComponent)componentPool.Pop()
            : new MultipleFieldsNamespacedComponent();
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static global::MyApp.Main.Entity RemoveMultipleFieldsNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(MyAppMainMultipleFieldsNamespacedComponentIndex.Index.Value);
        return entity;
    }

    public static MultipleFieldsNamespacedComponent GetMultipleFieldsNamespaced(this global::MyApp.Main.Entity entity)
    {
        return (MultipleFieldsNamespacedComponent)entity.GetComponent(MyAppMainMultipleFieldsNamespacedComponentIndex.Index.Value);
    }
}
}
