//HintName: MyApp.ContextInitialization.Initialize.ContextInitialization.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ContextInitializationMethod
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

namespace MyApp
{
public static partial class ContextInitialization
{
    public static partial void Initialize()
    {
        global::MyAppMainMultipleFieldsComponentIndex.Index = new ComponentIndex(0);
        global::MyFeature.MyAppMainAnotherNamespacedComponentIndex.Index = new ComponentIndex(1);
        global::MyFeature.MyAppMainAnyEventNamespacedComponentIndex.Index = new ComponentIndex(2);
        global::MyFeature.MyAppMainAnyAnyEventNamespacedAddedListenerComponentIndex.Index = new ComponentIndex(3);
        global::MyFeature.MyAppMainDuplicatedContextsNamespacedComponentIndex.Index = new ComponentIndex(4);
        global::MyFeature.MyAppMainMultipleFieldsNamespacedComponentIndex.Index = new ComponentIndex(5);
        global::MyFeature.MyAppMainMultiplePropertiesNamespacedComponentIndex.Index = new ComponentIndex(6);
        global::MyFeature.MyAppMainSelfEventNamespacedRemovedListenerComponentIndex.Index = new ComponentIndex(7);
        global::MyFeature.MyAppMainNonPublicComponentIndex.Index = new ComponentIndex(8);
        global::MyFeature.MyAppMainNoValidFieldsNamespacedComponentIndex.Index = new ComponentIndex(9);
        global::MyFeature.MyAppMainOneFieldNamespacedComponentIndex.Index = new ComponentIndex(10);
        global::MyFeature.MyAppMainReservedKeywordFieldsNamespacedComponentIndex.Index = new ComponentIndex(11);
        global::MyFeature.MyAppMainSelfEventNamespacedComponentIndex.Index = new ComponentIndex(12);
        global::MyFeature.MyAppMainSomeNamespacedComponentIndex.Index = new ComponentIndex(13);
        global::MyFeature.MyAppMainSomeNamespacedComponentIndex.Index = new ComponentIndex(14);
        global::MyFeature.MyAppMainUniqueNamespacedComponentIndex.Index = new ComponentIndex(15);
        global::MyFeature.MyAppMainUniqueOneFieldNamespacedComponentIndex.Index = new ComponentIndex(16);
        global::MyAppMainOneFieldComponentIndex.Index = new ComponentIndex(17);
        global::MyAppMainSomeComponentIndex.Index = new ComponentIndex(18);

        MyApp.MainContext.ComponentNames = new string[]
        {
            "MultipleFields",
            "MyFeature.AnotherNamespaced",
            "MyFeature.AnyEventNamespaced",
            "MyFeature.AnyMyAppMainAnyEventNamespacedAddedListener",
            "MyFeature.DuplicatedContextsNamespaced",
            "MyFeature.MultipleFieldsNamespaced",
            "MyFeature.MultiplePropertiesNamespaced",
            "MyFeature.MyAppMainSelfEventNamespacedRemovedListener",
            "MyFeature.NonPublic",
            "MyFeature.NoValidFieldsNamespaced",
            "MyFeature.OneFieldNamespaced",
            "MyFeature.ReservedKeywordFieldsNamespaced",
            "MyFeature.SelfEventNamespaced",
            "MyFeature.SomeNamespaced",
            "MyFeature.SomeNamespaced",
            "MyFeature.UniqueNamespaced",
            "MyFeature.UniqueOneFieldNamespaced",
            "OneField",
            "Some"
        };

        MyApp.MainContext.ComponentTypes = new global::System.Type[]
        {
            typeof(global::MultipleFieldsComponent),
            typeof(global::MyFeature.AnotherNamespacedComponent),
            typeof(global::MyFeature.AnyEventNamespacedComponent),
            typeof(global::MyFeature.AnyMyAppMainAnyEventNamespacedAddedListenerComponent),
            typeof(global::MyFeature.DuplicatedContextsNamespacedComponent),
            typeof(global::MyFeature.MultipleFieldsNamespacedComponent),
            typeof(global::MyFeature.MultiplePropertiesNamespacedComponent),
            typeof(global::MyFeature.MyAppMainSelfEventNamespacedRemovedListenerComponent),
            typeof(global::MyFeature.NonPublicComponent),
            typeof(global::MyFeature.NoValidFieldsNamespacedComponent),
            typeof(global::MyFeature.OneFieldNamespacedComponent),
            typeof(global::MyFeature.ReservedKeywordFieldsNamespacedComponent),
            typeof(global::MyFeature.SelfEventNamespacedComponent),
            typeof(global::MyFeature.SomeNamespacedComponent),
            typeof(global::MyFeature.SomeNamespacedComponent),
            typeof(global::MyFeature.UniqueNamespacedComponent),
            typeof(global::MyFeature.UniqueOneFieldNamespacedComponent),
            typeof(global::OneFieldComponent),
            typeof(global::SomeComponent)
        };
    }
}
}
