//HintName: MyFeature.MyAppMainOneFieldNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyFeature
{
public static class MyAppMainOneFieldNamespacedEntityExtension
{
    public static bool HasOneFieldNamespaced(this global::MyApp.Main.Entity entity)
    {
        return entity.HasComponent(MyAppMainOneFieldNamespacedComponentIndex.Index.Value);
    }

    public static global::MyApp.Main.Entity AddOneFieldNamespaced(this global::MyApp.Main.Entity entity, string value)
    {
        var index = MyAppMainOneFieldNamespacedComponentIndex.Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (OneFieldNamespacedComponent)componentPool.Pop()
            : new OneFieldNamespacedComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static global::MyApp.Main.Entity ReplaceOneFieldNamespaced(this global::MyApp.Main.Entity entity, string value)
    {
        var index = MyAppMainOneFieldNamespacedComponentIndex.Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (OneFieldNamespacedComponent)componentPool.Pop()
            : new OneFieldNamespacedComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static global::MyApp.Main.Entity RemoveOneFieldNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(MyAppMainOneFieldNamespacedComponentIndex.Index.Value);
        return entity;
    }

    public static OneFieldNamespacedComponent GetOneFieldNamespaced(this global::MyApp.Main.Entity entity)
    {
        return (OneFieldNamespacedComponent)entity.GetComponent(MyAppMainOneFieldNamespacedComponentIndex.Index.Value);
    }
}
}
