//HintName: MyApp.ContextInitialization.Initialize.ContextInitialization.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ContextInitializationMethod
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp
{
public static partial class ContextInitialization
{
    public static partial void Initialize()
    {


        global::EmptyContext.ComponentNames = new string[]
        {

        };

        global::EmptyContext.ComponentTypes = new global::System.Type[]
        {

        };
    }
}
}
