//HintName: MyFeature.MyAppMainAnyAnyEventNamespacedAddedListenerEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainAnyAnyEventNamespacedAddedListenerComponentIndex;

namespace MyFeature
{
public static class MyAppMainAnyAnyEventNamespacedAddedListenerEntityExtension
{
    public static bool HasAnyAnyEventNamespacedAddedListener(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddAnyAnyEventNamespacedAddedListener(this Entity entity, global::System.Collections.Generic.List<IAnyMyAppMainAnyEventNamespacedAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (AnyMyAppMainAnyEventNamespacedAddedListenerComponent)componentPool.Pop()
            : new AnyMyAppMainAnyEventNamespacedAddedListenerComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceAnyAnyEventNamespacedAddedListener(this Entity entity, global::System.Collections.Generic.List<IAnyMyAppMainAnyEventNamespacedAddedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (AnyMyAppMainAnyEventNamespacedAddedListenerComponent)componentPool.Pop()
            : new AnyMyAppMainAnyEventNamespacedAddedListenerComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveAnyAnyEventNamespacedAddedListener(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static AnyMyAppMainAnyEventNamespacedAddedListenerComponent GetAnyAnyEventNamespacedAddedListener(this Entity entity)
    {
        return (AnyMyAppMainAnyEventNamespacedAddedListenerComponent)entity.GetComponent(Index.Value);
    }
}
}
