//HintName: MyApp.MainContext.ContextInitializationMethod.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ContextInitializationMethod
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using MyApp.Main;

namespace MyApp
{
public static partial class ContextInitialization
{
    public static partial void Initialize()
    {


        MyApp.MainContext.ComponentNames = new string[]
        {

        };

        MyApp.MainContext.ComponentTypes = new System.Type[]
        {

        };
    }
}
}
