//HintName: MyFeature.UniqueOneFieldNamespacedComponent.MyApp.Main.ContextExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.ContextExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using global::MyApp.Main;

namespace MyFeature
{
public static class MyAppMainUniqueOneFieldNamespacedContextExtension
{
    public static Entity SetUniqueOneFieldNamespaced(this MyApp.MainContext context, string value)
    {
        var entity = context.GetUniqueOneFieldNamespacedEntity() ?? context.CreateEntity();
        entity.SetUniqueOneFieldNamespaced(value);
        return entity;
    }

    public static void UnsetUniqueOneFieldNamespaced(this MyApp.MainContext context)
    {
        context.GetUniqueOneFieldNamespacedEntity()?.Destroy();
    }

    public static Entity? GetUniqueOneFieldNamespacedEntity(this MyApp.MainContext context)
    {
        return context.GetGroup(MyAppMainUniqueOneFieldNamespacedMatcher.UniqueOneFieldNamespaced).GetSingleEntity();
    }

    public static UniqueOneFieldNamespacedComponent? GetUniqueOneFieldNamespaced(this MyApp.MainContext context)
    {
        return context.GetUniqueOneFieldNamespacedEntity()?.GetUniqueOneFieldNamespaced();
    }
}
}
