//HintName: MyApp.Main.MyFeatureAnotherNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using static MyApp.Main.MyFeatureAnotherNamespacedComponentIndex;

namespace MyApp.Main
{
public static class MyFeatureAnotherNamespacedEntityExtension
{
    static readonly MyFeature.AnotherNamespacedComponent SingleAnotherNamespacedComponent = new MyFeature.AnotherNamespacedComponent();

    public static bool HasAnotherNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddAnotherNamespaced(this Entity entity)
    {
        entity.AddComponent(Index.Value, SingleAnotherNamespacedComponent);
        return entity;
    }

    public static Entity ReplaceAnotherNamespaced(this Entity entity)
    {
        entity.ReplaceComponent(Index.Value, SingleAnotherNamespacedComponent);
        return entity;
    }

    public static Entity RemoveAnotherNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MyFeature.AnotherNamespacedComponent GetAnotherNamespaced(this Entity entity)
    {
        return (MyFeature.AnotherNamespacedComponent)entity.GetComponent(Index.Value);
    }
}
}
