//HintName: Other.MyAppMultipleFieldsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Other
{
public static class MyAppMultipleFieldsNamespacedEntityExtension
{
    public static bool HasMultipleFieldsNamespaced(this Other.Entity entity)
    {
        return entity.HasComponent(MyAppMultipleFieldsNamespacedComponentIndex.Value);
    }

    public static Other.Entity AddMultipleFieldsNamespaced(this Other.Entity entity, string value1, string value2, string value3)
    {
        var index = MyAppMultipleFieldsNamespacedComponentIndex.Value;
        var component = (MyApp.MultipleFieldsNamespacedComponent)entity.CreateComponent(index, typeof(MyApp.MultipleFieldsNamespacedComponent));
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Other.Entity ReplaceMultipleFieldsNamespaced(this Other.Entity entity, string value1, string value2, string value3)
    {
        var index = MyAppMultipleFieldsNamespacedComponentIndex.Value;
        var component = (MyApp.MultipleFieldsNamespacedComponent)entity.CreateComponent(index, typeof(MyApp.MultipleFieldsNamespacedComponent));
        component.Value1 = value1;
        component.Value2 = value2;
        component.Value3 = value3;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Other.Entity RemoveMultipleFieldsNamespaced(this Other.Entity entity)
    {
        entity.RemoveComponent(MyAppMultipleFieldsNamespacedComponentIndex.Value);
        return entity;
    }
}
}
