//HintName: MyFeature.MyAppMainDuplicatedContextsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyFeature
{
public static class MyAppMainDuplicatedContextsNamespacedEntityExtension
{
    static readonly DuplicatedContextsNamespacedComponent SingleDuplicatedContextsNamespacedComponent = new DuplicatedContextsNamespacedComponent();

    public static bool HasDuplicatedContextsNamespaced(this global::MyApp.Main.Entity entity)
    {
        return entity.HasComponent(MyAppMainDuplicatedContextsNamespacedComponentIndex.Index.Value);
    }

    public static global::MyApp.Main.Entity AddDuplicatedContextsNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.AddComponent(MyAppMainDuplicatedContextsNamespacedComponentIndex.Index.Value, SingleDuplicatedContextsNamespacedComponent);
        return entity;
    }

    public static global::MyApp.Main.Entity ReplaceDuplicatedContextsNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.ReplaceComponent(MyAppMainDuplicatedContextsNamespacedComponentIndex.Index.Value, SingleDuplicatedContextsNamespacedComponent);
        return entity;
    }

    public static global::MyApp.Main.Entity RemoveDuplicatedContextsNamespaced(this global::MyApp.Main.Entity entity)
    {
        entity.RemoveComponent(MyAppMainDuplicatedContextsNamespacedComponentIndex.Index.Value);
        return entity;
    }

    public static DuplicatedContextsNamespacedComponent GetDuplicatedContextsNamespaced(this global::MyApp.Main.Entity entity)
    {
        return (DuplicatedContextsNamespacedComponent)entity.GetComponent(MyAppMainDuplicatedContextsNamespacedComponentIndex.Index.Value);
    }
}
}
