//HintName: MyFeature.MyAppMainSelfEventNamespacedRemovedListenerEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;
using static global::MyFeature.MyAppMainSelfEventNamespacedRemovedListenerComponentIndex;

namespace MyFeature
{
public static class MyAppMainSelfEventNamespacedRemovedListenerEntityExtension
{
    public static bool HasSelfEventNamespacedRemovedListener(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddSelfEventNamespacedRemovedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainSelfEventNamespacedRemovedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainSelfEventNamespacedRemovedListenerComponent)componentPool.Pop()
            : new MyAppMainSelfEventNamespacedRemovedListenerComponent();
        component.Value = value;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceSelfEventNamespacedRemovedListener(this Entity entity, global::System.Collections.Generic.List<IMyAppMainSelfEventNamespacedRemovedListener> value)
    {
        var index = Index.Value;
        var componentPool = entity.GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyAppMainSelfEventNamespacedRemovedListenerComponent)componentPool.Pop()
            : new MyAppMainSelfEventNamespacedRemovedListenerComponent();
        component.Value = value;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveSelfEventNamespacedRemovedListener(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MyAppMainSelfEventNamespacedRemovedListenerComponent GetSelfEventNamespacedRemovedListener(this Entity entity)
    {
        return (MyAppMainSelfEventNamespacedRemovedListenerComponent)entity.GetComponent(Index.Value);
    }
}
}
