//HintName: MyApp.Main.MyFeatureReservedKeywordFieldsNamespacedEntityExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.EntityExtension
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using static MyApp.Main.MyFeatureReservedKeywordFieldsNamespacedComponentIndex;

namespace MyApp.Main
{
public static class MyFeatureReservedKeywordFieldsNamespacedEntityExtension
{
    public static bool HasReservedKeywordFieldsNamespaced(this Entity entity)
    {
        return entity.HasComponent(Index.Value);
    }

    public static Entity AddReservedKeywordFieldsNamespaced(this Entity entity, string @namespace, string @class, string @public)
    {
        var index = Index.Value;
        var component = (MyFeature.ReservedKeywordFieldsNamespacedComponent)entity.CreateComponent(index, typeof(MyFeature.ReservedKeywordFieldsNamespacedComponent));
        component.Namespace = @namespace;
        component.Class = @class;
        component.Public = @public;
        entity.AddComponent(index, component);
        return entity;
    }

    public static Entity ReplaceReservedKeywordFieldsNamespaced(this Entity entity, string @namespace, string @class, string @public)
    {
        var index = Index.Value;
        var component = (MyFeature.ReservedKeywordFieldsNamespacedComponent)entity.CreateComponent(index, typeof(MyFeature.ReservedKeywordFieldsNamespacedComponent));
        component.Namespace = @namespace;
        component.Class = @class;
        component.Public = @public;
        entity.ReplaceComponent(index, component);
        return entity;
    }

    public static Entity RemoveReservedKeywordFieldsNamespaced(this Entity entity)
    {
        entity.RemoveComponent(Index.Value);
        return entity;
    }

    public static MyFeature.ReservedKeywordFieldsNamespacedComponent GetReservedKeywordFieldsNamespaced(this Entity entity)
    {
        return (MyFeature.ReservedKeywordFieldsNamespacedComponent)entity.GetComponent(Index.Value);
    }

    public static void Deconstruct(this MyFeature.ReservedKeywordFieldsNamespacedComponent component, out string @namespace, out string @class, out string @public)
    {
        @namespace = component.Namespace;
        @class = component.Class;
        @public = component.Public;
    }
}
}
