//HintName: MyAppMainEventAddedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::MyApp.Main;

public interface IMyAppMainEventAddedListener
{
    void OnEventAdded(Entity entity, string value);
}

public sealed class MyAppMainEventAddedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainEventAddedListener> Value;
}

public static class MyAppMainEventAddedListenerEventEntityExtension
{
    public static Entity AddEventAddedListener(this Entity entity, IMyAppMainEventAddedListener value)
    {
        var listeners = entity.HasEventAddedListener()
            ? entity.GetEventAddedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainEventAddedListener>();
        listeners.Add(value);
        return entity.ReplaceEventAddedListener(listeners);
    }

    public static void RemoveEventAddedListener(this Entity entity, IMyAppMainEventAddedListener value, bool removeListenerWhenEmpty = true)
    {
        var listeners = entity.GetEventAddedListener().Value;
        listeners.Remove(value);
        if (removeListenerWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveEventAddedListener();
            if (entity.IsEmpty())
                entity.Destroy();
        }
        else
        {
            entity.ReplaceEventAddedListener(listeners);
        }
    }
}

public sealed class MyAppMainEventAddedEventSystem : global::Entitas.ReactiveSystem<Entity>
{
    readonly global::System.Collections.Generic.List<IMyAppMainEventAddedListener> _listenerBuffer;

    public MyAppMainEventAddedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainEventAddedListener>();
    }

    protected override global::Entitas.ICollector<Entity> GetTrigger(global::Entitas.IContext<Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Added(MyAppMainEventMatcher.Event)
        );
    }

    protected override bool Filter(Entity entity)
    {
        return entity.HasEvent() && entity.HasEventAddedListener();
    }

    protected override void Execute(global::System.Collections.Generic.List<Entity> entities)
    {
        foreach (var entity in entities)
        {
            var component = entity.GetEvent();
            _listenerBuffer.Clear();
            _listenerBuffer.AddRange(entity.GetEventAddedListener().Value);
            foreach (var listener in _listenerBuffer)
            {
                listener.OnEventAdded(entity, component.Value);
            }
        }
    }
}
