//HintName: MyAppMainAnyFlagEventAddedListenerComponent.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ComponentGenerator.Events
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public interface IMyAppMainAnyFlagEventAddedListener
{
    void OnAnyFlagEventAdded(global::MyApp.Main.Entity entity);
}

public sealed class MyAppMainAnyFlagEventAddedListenerComponent : global::Entitas.IComponent
{
    public global::System.Collections.Generic.List<IMyAppMainAnyFlagEventAddedListener> Value;
}

public static class MyAppMainAnyFlagEventAddedListenerEventEntityExtension
{
    public static global::MyApp.Main.Entity AddAnyFlagEventAddedListener(this global::MyApp.Main.Entity entity, IMyAppMainAnyFlagEventAddedListener value)
    {
        var listeners = entity.HasAnyFlagEventAddedListener()
            ? entity.GetAnyFlagEventAddedListener().Value
            : new global::System.Collections.Generic.List<IMyAppMainAnyFlagEventAddedListener>();
        listeners.Add(value);
        return entity.ReplaceAnyFlagEventAddedListener(listeners);
    }

    public static void RemoveAnyFlagEventAddedListener(this global::MyApp.Main.Entity entity, IMyAppMainAnyFlagEventAddedListener value, bool removeListenerWhenEmpty = true)
    {
        var listeners = entity.GetAnyFlagEventAddedListener().Value;
        listeners.Remove(value);
        if (removeListenerWhenEmpty && listeners.Count == 0)
        {
            entity.RemoveAnyFlagEventAddedListener();
            if (entity.IsEmpty())
                entity.Destroy();
        }
        else
        {
            entity.ReplaceAnyFlagEventAddedListener(listeners);
        }
    }
}

public sealed class MyAppMainAnyFlagEventAddedEventSystem : global::Entitas.ReactiveSystem<global::MyApp.Main.Entity>
{
    readonly global::Entitas.IGroup<global::MyApp.Main.Entity> _listeners;
    readonly global::System.Collections.Generic.List<global::MyApp.Main.Entity> _entityBuffer;
    readonly global::System.Collections.Generic.List<IMyAppMainAnyFlagEventAddedListener> _listenerBuffer;

    public MyAppMainAnyFlagEventAddedEventSystem(MyApp.MainContext context) : base(context)
    {
        _listeners = context.GetGroup(MyAppMainAnyFlagEventAddedListenerMatcher.AnyFlagEventAddedListener);
        _entityBuffer = new global::System.Collections.Generic.List<global::MyApp.Main.Entity>();
        _listenerBuffer = new global::System.Collections.Generic.List<IMyAppMainAnyFlagEventAddedListener>();
    }

    protected override global::Entitas.ICollector<global::MyApp.Main.Entity> GetTrigger(global::Entitas.IContext<global::MyApp.Main.Entity> context)
    {
        return global::Entitas.CollectorContextExtension.CreateCollector(
            context, global::Entitas.TriggerOnEventMatcherExtension.Added(MyAppMainFlagEventMatcher.FlagEvent)
        );
    }

    protected override bool Filter(global::MyApp.Main.Entity entity)
    {
        return entity.HasFlagEvent();
    }

    protected override void Execute(global::System.Collections.Generic.List<global::MyApp.Main.Entity> entities)
    {
        foreach (var entity in entities)
        {
            foreach (var listenerEntity in _listeners.GetEntities(_entityBuffer))
            {
                _listenerBuffer.Clear();
                _listenerBuffer.AddRange(listenerEntity.GetAnyFlagEventAddedListener().Value);
                foreach (var listener in _listenerBuffer)
                {
                    listener.OnAnyFlagEventAdded(entity);
                }
            }
        }
    }
}
