//HintName: Entitas.Generators.Tests.Fixtures.Contexts.Namespaced.Matcher.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ContextGenerator.Matcher
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas.Generators.Tests.Fixtures.Contexts.Namespaced
{
public static class Matcher
{
    public static Entitas.IAllOfMatcher<Namespaced.Entity> AllOf(params int[] indices)
    {
        return Entitas.Matcher<Namespaced.Entity>.AllOf(indices);
    }

    public static Entitas.IAnyOfMatcher<Namespaced.Entity> AnyOf(params int[] indices)
    {
        return Entitas.Matcher<Namespaced.Entity>.AnyOf(indices);
    }
}
}
