//HintName: Entitas.Generators.Tests.Fixtures.Contexts.NamespacedEntity.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ContextGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas.Generators.Tests.Fixtures.Contexts;

public sealed partial class NamespacedEntity : Entitas.Entity { }
