//HintName: Entitas.Generators.Tests.Fixtures.Contexts.NamespacedContext.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ContextGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas.Generators.Tests.Fixtures.Contexts;

public sealed partial class NamespacedContext : Entitas.Context<NamespacedEntity>
{
    public NamespacedContext()
        : base(
            0,
            0,
            new Entitas.ContextInfo(
                "Namespaced",
                null,
                null
            ),
            entity =>
#if (ENTITAS_FAST_AND_UNSAFE)
                new Entitas.UnsafeAERC(),
#else
                new Entitas.SafeAERC(entity),
#endif
            () => new NamespacedEntity()
        ) { }
}
