//HintName: SomeContext.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ContextGenerator.Context
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class SomeContext : global::Entitas.Context<Some.Entity>
{
    public static string[] ComponentNames;
    public static global::System.Type[] ComponentTypes;

    public SomeContext()
        : base(
            ComponentTypes.Length,
            0,
            new global::Entitas.ContextInfo(
                "SomeContext",
                ComponentNames,
                ComponentTypes
            ),
            entity =>
#if (ENTITAS_FAST_AND_UNSAFE)
                new global::Entitas.UnsafeAERC(),
#else
                new global::Entitas.SafeAERC(entity),
#endif
            () => new Some.Entity()
        ) { }
}
