//HintName: Some.Matcher.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ContextGenerator.Matcher
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Some
{
public static class Matcher
{
    public static global::Entitas.IAllOfMatcher<Entity> AllOf(params int[] indices)
    {
        return global::Entitas.Matcher<Entity>.AllOf(indices);
    }

    public static global::Entitas.IAllOfMatcher<Entity> AllOf(params global::Entitas.IMatcher<Entity>[] matchers)
    {
        return global::Entitas.Matcher<Entity>.AllOf(matchers);
    }

    public static global::Entitas.IAnyOfMatcher<Entity> AnyOf(params int[] indices)
    {
        return global::Entitas.Matcher<Entity>.AnyOf(indices);
    }

    public static global::Entitas.IAnyOfMatcher<Entity> AnyOf(params global::Entitas.IMatcher<Entity>[] matchers)
    {
        return global::Entitas.Matcher<Entity>.AnyOf(matchers);
    }
}
}
