//HintName: MyApp.NamespacedContext.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ContextGenerator.Context
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp
{
public sealed partial class NamespacedContext : global::Entitas.Context<Namespaced.Entity>
{
    public static string[] ComponentNames;
    public static global::System.Type[] ComponentTypes;

    public NamespacedContext() :
        base(
            ComponentTypes.Length,
            0,
            new global::Entitas.ContextInfo(
                "MyApp.NamespacedContext",
                ComponentNames,
                ComponentTypes
            ),
#if (ENTITAS_FAST_AND_UNSAFE)
            global::Entitas.UnsafeAERC.Delegate,
#else
            global::Entitas.SafeAERC.Delegate,
#endif
            () => new Namespaced.Entity()
        ) { }
}
}
