//HintName: MyApp.Namespaced.ContextAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ContextGenerator.ContextAttribute
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyApp.Namespaced
{
public sealed class ContextAttribute : Entitas.Generators.Attributes.ContextAttribute
{
    public ContextAttribute() : base("MyApp.NamespacedContext") { }
}
}
