//HintName: Some.Matcher.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ContextGenerator.Matcher
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Some
{
public static class Matcher
{
    public static global::Entitas.IAllOfMatcher<Entity> AllOf(global::System.Span<ComponentIndex> indices)
    {
        return global::Entitas.Matcher<Entity>.AllOf(ToIntArray(indices));
    }

    public static global::Entitas.IAnyOfMatcher<Entity> AnyOf(global::System.Span<ComponentIndex> indices)
    {
        return global::Entitas.Matcher<Entity>.AnyOf(ToIntArray(indices));
    }

    public static global::Entitas.IAnyOfMatcher<Entity> AnyOf(this global::Entitas.IAllOfMatcher<Entity> matcher, global::System.Span<ComponentIndex> indices)
    {
        return matcher.AnyOf(ToIntArray(indices));
    }

    public static global::Entitas.INoneOfMatcher<Entity> NoneOf(this global::Entitas.IAnyOfMatcher<Entity> matcher, global::System.Span<ComponentIndex> indices)
    {
        return matcher.NoneOf(ToIntArray(indices));
    }

    static int[] ToIntArray(global::System.Span<ComponentIndex> indices)
    {
        var ints = new int[indices.Length];
        for (var i = 0; i < indices.Length; i++)
            ints[i] = indices[i].Value;

        return ints;
    }
}
}
