//HintName: Some.ContextInitializationAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ContextGenerator.ContextInitializationAttribute
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Some
{
[System.Diagnostics.Conditional("false")]
[System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = true)]
public sealed class ContextInitializationAttribute : System.Attribute { }
}
