//HintName: Some.ContextAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by
//     Entitas.Generators.ContextGenerator.ContextAttribute
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Some
{
[global::System.Diagnostics.Conditional("false")]
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
public sealed class ContextAttribute : global::System.Attribute { }
}
