#!/bin/bash -e
source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/vars"

build_project() {
  xbuild /target:Clean /property:Configuration=Release $PROJECT
  xbuild /property:Configuration=Release $PROJECT
}

${SCRIPTS}/generate_unity_csharp_project
run build_project "Building project ${PROJECT}"
