#!/bin/bash -e
SCRIPTS="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
ROOT="$SCRIPTS/.."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
PROJECT_NAME="Entitas"

ADDONS="$ROOT/Addons"
ADDONS_TEST="$ROOT/Tests/Unity"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

SOLUTION="$ROOT/$PROJECT_NAME.sln"
PROJECT_VERSION=`cat $ROOT/$PROJECT_NAME/$PROJECT_NAME/version`
DNS=$PROJECT_NAME
BIN="bin/Release"

TEST_PROJECT="$ROOT/Tests/Tests/Tests.csproj"
TEST_RUNNER="$ROOT/Tests/Tests/$BIN/Tests.exe"

# build
BUILD="$ROOT/Build"
BUILD_SRC="$BUILD/src"
BUILD_DOCS="$BUILD/docs"
BUILD_DEPLOY="$BUILD/deploy"

DOCS="$ROOT/docs"
DOCS_RES="$SCRIPTS/docs_resources"
DOCSET="com.sschmid.$PROJECT_NAME.docset"
DOCSET_KEY="entitas"

cpe() {
  rsync -ar --include-from "$SCRIPTS/rsync_include.txt" --exclude-from "$SCRIPTS/rsync_exclude.txt" $1 $2
}

cp_dll() {
    cp "$ROOT/$1/$BIN/$1.dll" $2
}

cp_exe() {
    cp "$ROOT/$1/$BIN/$1.exe" $2
}
