#!/bin/bash -e
SCRIPTS="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
ROOT="${SCRIPTS}/.."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
UNITY="/Applications/Unity/Unity.app/Contents/MacOS/Unity"
PROJECT_NAME="Entitas"

ADDONS="${ROOT}/Addons"
ADDONS_PLAYGROUND="${ADDONS}/Tests"

ES="Entitas"
ES_UE="Entitas.Unity.Editor"

ES_CG="Entitas.CodeGenerator"
ES_CG_ATTR="Entitas.CodeGenerator.Attributes"
ES_CG_CLI="Entitas.CodeGenerator.CLI"
ES_CG_UE="Entitas.CodeGenerator.Unity.Editor"

ES_MIG="Entitas.Migration"
ES_MIG_CLI="Entitas.Migration.CLI"
ES_MIG_UE="Entitas.Migration.Unity.Editor"

ES_VD_U="Entitas.VisualDebugging.Unity"
ES_VD_UE="Entitas.VisualDebugging.Unity.Editor"

ES_BP="Entitas.Blueprints"
ES_BP_U="Entitas.Blueprints.Unity"
ES_BP_UE="Entitas.Blueprints.Unity.Editor"

BIN="bin/Release"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

SOLUTION="${ROOT}/${PROJECT_NAME}.sln"
PROJECT_VERSION=`cat ${ROOT}/${PROJECT_NAME}/${PROJECT_NAME}/version`

TEST_PROJECT="${ROOT}/Tests/Tests/Tests.csproj"
TEST_RUNNER="${ROOT}/Tests/Tests/bin/Release/Tests.exe"

# build
BUILD="${ROOT}/Build"
BUILD_SRC="${BUILD}/src"
BUILD_DOCS="${BUILD}/docs"
BUILD_DEPLOY="${BUILD}/deploy"

DOCS="$ROOT/docs"
DOCS_RES="${SCRIPTS}/docs_resources"
DOCSET="com.sschmid.${PROJECT_NAME}.docset"
DOCSET_KEY="entitas"

cpe() {
  rsync -ar --include-from "${SCRIPTS}/rsync_include.txt" --exclude-from "${SCRIPTS}/rsync_exclude.txt" $1 $2
}
