#!/bin/bash -e
SCRIPTS="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
ROOT="${SCRIPTS}/.."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
UNITY="/Applications/Unity/Unity.app/Contents/MacOS/Unity"
PROJECT_NAME="Entitas"

PLUGINS="${ROOT}/Plugins"

ES="${PROJECT_NAME}"
BP="${ES}.Blueprints"
CG="${ES}.CodeGenerator"
CGA="${ES}.CodeGenerator.Api"
MIG="${ES}.Migration"

EU="${ES}.Unity"
UBP="${EU}.Blueprints"
UCG="${EU}.CodeGenerator"
UMIG="${EU}.Migration"
UVD="${EU}.VisualDebugging"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

SOLUTION="${ROOT}/${PROJECT_NAME}.sln"
PROJECT_VERSION=`cat ${ROOT}/${PROJECT_NAME}/${PROJECT_NAME}/version`

UNITY_EXECUTE_METHOD="Commands.GenerateCSharpProject"

TEST_PROJECT="${ROOT}/Tests/Tests/Tests.csproj"
TEST_RUNNER="${ROOT}/Tests/Tests/bin/Release/Tests.exe"

# build
BUILD="${ROOT}/Build"
BUILD_SRC="${BUILD}/src"
BUILD_DOCS="${BUILD}/docs"
BUILD_DEPLOY="${BUILD}/deploy"

DOCS="$ROOT/docs"
DOCS_RES="${SCRIPTS}/docs_resources"
DOCSET="com.sschmid.${PROJECT_NAME}.docset"
DOCSET_KEY="entitas"

cpe() {
  rsync -ar --include-from "${SCRIPTS}/rsync_include.txt" --exclude-from "${SCRIPTS}/rsync_exclude.txt" $1 $2
}
