#!/bin/bash -e
source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/vars"
${SCRIPTS}/update_project_dependencies
echo "### Generating C# project... -==========================================="
$UNITY -quit -batchmode -logfile -projectPath "$ROOT/$ESU_ASSETS/../" -executeMethod Commands.GenerateCSharpProject
echo "### Generating C# project done -========================================="
