#!/bin/bash -e
echo $0
source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/consts"

${SCRIPTS}/build
${SCRIPTS}/test
${SCRIPTS}/docs

# collect
cp -v "${ROOT}/${MIG}/bin/Release/Entitas.Migration.exe" "${BUILD_SRC}/MigrationAssistant.exe"
cp -v "${ROOT}/README.md" "$BUILD_SRC/README.md"
cp -v "${ROOT}/RELEASE_NOTES.md" "$BUILD_SRC/RELEASE_NOTES.md"
cp -v "${ROOT}/EntitasUpgradeGuide.md" "$BUILD_SRC/EntitasUpgradeGuide.md"
cp -v "${ROOT}/LICENSE.txt" "$BUILD_SRC/LICENSE.txt"

TMP_DIR="${BUILD}/tmp"

# create zip
mkdir $TMP_DIR
cp -r "${BUILD_SRC}/${PROJECT_NAME}" $TMP_DIR
cp "${BUILD_SRC}/"* $TMP_DIR || true
cp -r "$BUILD_DOCS/html/" "${TMP_DIR}/Documentation"
pushd $TMP_DIR > /dev/null
  zip -rq "${BUILD_DEPLOY}/${PROJECT_NAME}-CSharp.zip" ./
popd > /dev/null
rm -rf $TMP_DIR

# create unity zip
mkdir $TMP_DIR
cp -r "${BUILD_SRC}/"* $TMP_DIR || true
EDITOR="${TMP_DIR}/Editor"
mkdir $EDITOR
mv "${TMP_DIR}/Entitas/CodeGenerator/"* $EDITOR
mv {"${EDITOR}/Attributes",$EDITOR} "${TMP_DIR}/Entitas/CodeGenerator"
mkdir "${TMP_DIR}/${PROJECT_NAME}/Migration/"
mv "${TMP_DIR}/${MIG}/" "${TMP_DIR}/${PROJECT_NAME}/Migration/Editor/"
mv "${TMP_DIR}/${UNITY_PROJECT}/" "${TMP_DIR}/${PROJECT_NAME}/Unity/"
cp -r "$BUILD_DOCS/html/" "${TMP_DIR}/Documentation"
pushd $TMP_DIR > /dev/null
  zip -rq "${BUILD_DEPLOY}/${PROJECT_NAME}-Unity.zip" ./
popd > /dev/null
rm -rf $TMP_DIR

# create docset tgz
pushd "${BUILD_DOCS}/docset" > /dev/null
tar --exclude='.DS_Store' -czf "${BUILD_DEPLOY}/${PROJECT_NAME}.docset.tgz" $PROJECT_NAME.docset
popd > /dev/null

# generate tree file
TREE_IGNORE="bin|obj|Library|Libraries|*Tests|Readme|ProjectSettings|Build|docs|Temp|Examples|*.csproj|*.meta|*.sln|*.userprefs|*.properties"
pushd $ROOT > /dev/null
  tree -I $TREE_IGNORE --noreport -d > tree.txt
  tree -I $TREE_IGNORE --noreport --dirsfirst >> tree.txt
  cat tree.txt
popd > /dev/null
