#!/bin/bash -e
source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/vars"

release() {
  pushd ${SCRIPTS} > /dev/null
    ./build_project
    ./run_tests
    ./run_unity_tests
    ./generate_docs
    ./post_build_collect
    ./generate_tree_file
    ./deploy
  popd > /dev/null
}

run release "Releasing"