#!/bin/bash -e
source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/vars"
echo "### Releasing... -======================================================="
pushd ${SCRIPTS} > /dev/null
./build
./run_tests
./run_unity_tests
./generate_docs
./post_build_collect
./generate_tree_file
./deploy
popd > /dev/null
echo "### Releasing done -====================================================="
