#!/bin/bash
source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/vars"

run_unity_tests() {
  $UNITY -quit -batchmode -runEditorTests -projectPath "$ROOT/$ESU_ASSETS/../" -editorTestsResultFile "${ROOT}/unity-test-results.xml"
  TEST_RESULT=$?
  echo `cat "${ROOT}/unity-test-results.xml"`
  echo $TEST_RESULT
  echo "Exit with ${TEST_RESULT}"
  exit $TEST_RESULT
}

run run_unity_tests "Running Unity tests"