#!/bin/bash -e
source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/vars"

update_project_dependencies() {
  rm -rf "${ROOT}/${ESU_LIBS}"
  mkdir "${ROOT}/${ESU_LIBS}"
  cpe "${BUILD_SRC}/${ES}" "${ROOT}/${ESU_LIBS}"
  cpe "${BUILD_SRC}/${MIG}" "${ROOT}/${ESU_LIBS}"
}

${SCRIPTS}/collect_sources
run update_project_dependencies "Updating project dependencies"