#!/bin/bash -e
echo $0
source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/consts"

# clean
rm -rf $BUILD

# create folder structure
mkdir $BUILD $BUILD_SRC $BUILD_DOCS $BUILD_DEPLOY

# collect sources
cpe "${ROOT}/${ES}/${ES}" $BUILD_SRC

cpe "${ADDONS}/${BP}/${BP}" $BUILD_SRC
cpe "${ADDONS}/${CG}/${CG}" $BUILD_SRC
cpe "${ADDONS}/${CGA}/${CGA}" $BUILD_SRC
cpe "${ADDONS}/${MIG}/${MIG}" $BUILD_SRC

cpe "${ADDONS}/${EU}/Assets/${EU}/" "${BUILD_SRC}/${EU}"
cpe "${ADDONS}/${UBP}/Assets/${UBP}/" "${BUILD_SRC}/${UBP}"
cpe "${ADDONS}/${UCG}/Assets/${UCG}/" "${BUILD_SRC}/${UCG}"
cpe "${ADDONS}/${UMIG}/Assets/${UMIG}/" "${BUILD_SRC}/${UMIG}"
cpe "${ADDONS}/${UVD}/Assets/${UVD}/" "${BUILD_SRC}/${UVD}"

# update project dependencies

# Entitas.Unity.Blueprints
libDir="${ADDONS}/${EU}/Assets/Libraries"
rm -rf ${libDir}
mkdir ${libDir}
cpe "${BUILD_SRC}/${ES}" ${libDir}

# Entitas.Unity.Blueprints
libDir="${ADDONS}/${UBP}/Assets/Libraries"
rm -rf ${libDir}
mkdir ${libDir}
cpe "${BUILD_SRC}/${ES}" ${libDir}
cpe "${BUILD_SRC}/${BP}" ${libDir}
cpe "${BUILD_SRC}/${CG}" "${libDir}/Editor"
cpe "${BUILD_SRC}/${CGA}" ${libDir}
cpe "${BUILD_SRC}/${EU}" ${libDir}
cpe "${BUILD_SRC}/${UCG}" ${libDir}
cpe "${BUILD_SRC}/${UVD}" ${libDir}

# Entitas.Unity.CodeGenerator
libDir="${ADDONS}/${UCG}/Assets/Libraries"
rm -rf ${libDir}
mkdir ${libDir}
cpe "${BUILD_SRC}/${ES}" ${libDir}
cpe "${BUILD_SRC}/${CG}" "${libDir}/Editor"
cpe "${BUILD_SRC}/${CGA}" ${libDir}
cpe "${BUILD_SRC}/${EU}" ${libDir}

# Entitas.Unity.Migration
libDir="${ADDONS}/${UMIG}/Assets/Libraries"
rm -rf ${libDir}
mkdir ${libDir}
cpe "${BUILD_SRC}/${ES}" ${libDir}
cpe "${BUILD_SRC}/${MIG}" ${libDir}
cpe "${BUILD_SRC}/${EU}" ${libDir}

# Entitas.Unity.VisualDebugging
libDir="${ADDONS}/${UVD}/Assets/Libraries"
rm -rf ${libDir}
mkdir ${libDir}
cpe "${BUILD_SRC}/${ES}" ${libDir}
cpe "${BUILD_SRC}/${CG}" "${libDir}/Editor"
cpe "${BUILD_SRC}/${CGA}" ${libDir}
cpe "${BUILD_SRC}/${EU}" ${libDir}
cpe "${BUILD_SRC}/${UCG}" ${libDir}
