#!/bin/bash -e
echo $0
source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/consts"

xbuild /property:Configuration=Release /verbosity:minimal $SOLUTION

# clean
rm -rf $BUILD

# create folder structure
mkdir $BUILD $BUILD_SRC $BUILD_DOCS $BUILD_DEPLOY

# collect sources
cp "${ADDONS}/Libraries/fabl.dll" ${BUILD_SRC}
cp "${ADDONS}/Libraries/fabl.Appenders.dll" ${BUILD_SRC}

cp "${ES}/${BIN}/${ES}.dll" ${BUILD_SRC}
cp "${ES_UTILS}/${BIN}/${ES_UTILS}.dll" ${BUILD_SRC}

cp "${ADDONS}/${ES_U}/${BIN}/${ES_U}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_UE}/${BIN}/${ES_UE}.dll" ${BUILD_SRC}

cp "${ADDONS}/${ES_CG}/${BIN}/${ES_CG}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_CG_ATTR}/${BIN}/${ES_CG_ATTR}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_CG_G}/${BIN}/${ES_CG_G}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_CG_G_CLI}/${BIN}/${ES_CG_G_CLI}.exe" ${BUILD_SRC}
cp "${ADDONS}/${ES_CG_P}/${BIN}/${ES_CG_P}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_CG_UE}/${BIN}/${ES_CG_UE}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_CG_UE}/Compile.cs" ${BUILD_SRC}

cp "${ADDONS}/${ES_MIG}/${BIN}/${ES_MIG}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_MIG_CLI}/${BIN}/${ES_MIG_CLI}.exe" ${BUILD_SRC}
cp "${ADDONS}/${ES_MIG_UE}/${BIN}/${ES_MIG_UE}.dll" ${BUILD_SRC}

cp "${ADDONS}/${ES_VD_CG_P}/${BIN}/${ES_VD_CG_P}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_VD_U}/${BIN}/${ES_VD_U}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_VD_UE}/${BIN}/${ES_VD_UE}.dll" ${BUILD_SRC}

cp "${ADDONS}/${ES_BP}/${BIN}/${ES_BP}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_BP_CG_P}/${BIN}/${ES_BP_CG_P}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_BP_U}/${BIN}/${ES_BP_U}.dll" ${BUILD_SRC}
cp "${ADDONS}/${ES_BP_UE}/${BIN}/${ES_BP_UE}.dll" ${BUILD_SRC}


# update project dependencies

# Entitas.Unity
libDir="${ADDONS_PLAYGROUND}/Entitas.Unity/Assets/Libraries"
rm -rf ${libDir}
mkdir ${libDir}
mkdir "${libDir}/Editor"
cp "${BUILD_SRC}/${ES}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_UTILS}.dll" ${libDir}

# CodeGeneration
libDir="${ADDONS_PLAYGROUND}/CodeGenerator/Assets/Libraries"
rm -rf ${libDir}
mkdir ${libDir}
mkdir "${libDir}/Editor"
cp "${BUILD_SRC}/${ES_CG_G}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_CG}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_CG_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_UTILS}.dll" ${libDir}
cp "${BUILD_SRC}/fabl.dll" ${libDir}
cp "${BUILD_SRC}/fabl.Appenders.dll" ${libDir}
# --
cp "${BUILD_SRC}/${ES_CG_ATTR}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_CG_P}.dll" "${libDir}/Editor/"

# Migration
libDir="${ADDONS_PLAYGROUND}/Migration/Assets/Libraries"
rm -rf ${libDir}
mkdir ${libDir}
mkdir "${libDir}/Editor"
cp "${BUILD_SRC}/${ES}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_MIG}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_MIG_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_UTILS}.dll" ${libDir}

# VisualDebugging
libDir="${ADDONS_PLAYGROUND}/VisualDebugging/Assets/Libraries"
rm -rf ${libDir}
mkdir ${libDir}
mkdir "${libDir}/Editor"
cp "${BUILD_SRC}/${ES_CG_ATTR}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_CG_G}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_CG}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_CG_P}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_U}.dll" "${libDir}"
cp "${BUILD_SRC}/${ES_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_UTILS}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_VD_U}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_VD_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/fabl.dll" ${libDir}
cp "${BUILD_SRC}/fabl.Appenders.dll" ${libDir}
# --
cp "${BUILD_SRC}/${ES_CG_ATTR}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_CG_P}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_CG_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_VD_CG_P}.dll" "${libDir}/Editor/"

# Blueprints
libDir="${ADDONS_PLAYGROUND}/Blueprints/Assets/Libraries"
rm -rf ${libDir}
mkdir ${libDir}
mkdir "${libDir}/Editor"
cp "${BUILD_SRC}/${ES_BP}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_BP_U}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_BP_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_CG_ATTR}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_CG_G}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_CG}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_CG_P}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_UTILS}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_VD_U}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_VD_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/fabl.dll" ${libDir}
cp "${BUILD_SRC}/fabl.Appenders.dll" ${libDir}
# --
cp "${BUILD_SRC}/${ES_CG_ATTR}.dll" ${libDir}
cp "${BUILD_SRC}/${ES_CG_P}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_CG_UE}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_VD_CG_P}.dll" "${libDir}/Editor/"
cp "${BUILD_SRC}/${ES_BP_CG_P}.dll" "${libDir}/Editor/"
